// This models a linear cable comprising of 100 compartments
// all with default field values.
// It uses the hsolver to solve the cable.
create neutral /cell
create compartment /cell/d0
create compartment /cell/d1
create compartment /cell/d2
create compartment /cell/d3
create compartment /cell/d4
create compartment /cell/d5
create compartment /cell/d6
create compartment /cell/d7
create compartment /cell/d8
create compartment /cell/d9
create compartment /cell/d10
create compartment /cell/d11
create compartment /cell/d12
create compartment /cell/d13
create compartment /cell/d14
create compartment /cell/d15
create compartment /cell/d16
create compartment /cell/d17
create compartment /cell/d18
create compartment /cell/d19
create compartment /cell/d20
create compartment /cell/d21
create compartment /cell/d22
create compartment /cell/d23
create compartment /cell/d24
create compartment /cell/d25
create compartment /cell/d26
create compartment /cell/d27
create compartment /cell/d28
create compartment /cell/d29
create compartment /cell/d30
create compartment /cell/d31
create compartment /cell/d32
create compartment /cell/d33
create compartment /cell/d34
create compartment /cell/d35
create compartment /cell/d36
create compartment /cell/d37
create compartment /cell/d38
create compartment /cell/d39
create compartment /cell/d40
create compartment /cell/d41
create compartment /cell/d42
create compartment /cell/d43
create compartment /cell/d44
create compartment /cell/d45
create compartment /cell/d46
create compartment /cell/d47
create compartment /cell/d48
create compartment /cell/d49
create compartment /cell/d50
create compartment /cell/d51
create compartment /cell/d52
create compartment /cell/d53
create compartment /cell/d54
create compartment /cell/d55
create compartment /cell/d56
create compartment /cell/d57
create compartment /cell/d58
create compartment /cell/d59
create compartment /cell/d60
create compartment /cell/d61
create compartment /cell/d62
create compartment /cell/d63
create compartment /cell/d64
create compartment /cell/d65
create compartment /cell/d66
create compartment /cell/d67
create compartment /cell/d68
create compartment /cell/d69
create compartment /cell/d70
create compartment /cell/d71
create compartment /cell/d72
create compartment /cell/d73
create compartment /cell/d74
create compartment /cell/d75
create compartment /cell/d76
create compartment /cell/d77
create compartment /cell/d78
create compartment /cell/d79
create compartment /cell/d80
create compartment /cell/d81
create compartment /cell/d82
create compartment /cell/d83
create compartment /cell/d84
create compartment /cell/d85
create compartment /cell/d86
create compartment /cell/d87
create compartment /cell/d88
create compartment /cell/d89
create compartment /cell/d90
create compartment /cell/d91
create compartment /cell/d92
create compartment /cell/d93
create compartment /cell/d94
create compartment /cell/d95
create compartment /cell/d96
create compartment /cell/d97
create compartment /cell/d98
create compartment /cell/d99

addmsg /cell/d0/raxial /cell/d1/axial
addmsg /cell/d1/raxial /cell/d2/axial
addmsg /cell/d2/raxial /cell/d3/axial
addmsg /cell/d3/raxial /cell/d4/axial
addmsg /cell/d4/raxial /cell/d5/axial
addmsg /cell/d5/raxial /cell/d6/axial
addmsg /cell/d6/raxial /cell/d7/axial
addmsg /cell/d7/raxial /cell/d8/axial
addmsg /cell/d8/raxial /cell/d9/axial
addmsg /cell/d9/raxial /cell/d10/axial
addmsg /cell/d10/raxial /cell/d11/axial
addmsg /cell/d11/raxial /cell/d12/axial
addmsg /cell/d12/raxial /cell/d13/axial
addmsg /cell/d13/raxial /cell/d14/axial
addmsg /cell/d14/raxial /cell/d15/axial
addmsg /cell/d15/raxial /cell/d16/axial
addmsg /cell/d16/raxial /cell/d17/axial
addmsg /cell/d17/raxial /cell/d18/axial
addmsg /cell/d18/raxial /cell/d19/axial
addmsg /cell/d19/raxial /cell/d20/axial
addmsg /cell/d20/raxial /cell/d21/axial
addmsg /cell/d21/raxial /cell/d22/axial
addmsg /cell/d22/raxial /cell/d23/axial
addmsg /cell/d23/raxial /cell/d24/axial
addmsg /cell/d24/raxial /cell/d25/axial
addmsg /cell/d25/raxial /cell/d26/axial
addmsg /cell/d26/raxial /cell/d27/axial
addmsg /cell/d27/raxial /cell/d28/axial
addmsg /cell/d28/raxial /cell/d29/axial
addmsg /cell/d29/raxial /cell/d30/axial
addmsg /cell/d30/raxial /cell/d31/axial
addmsg /cell/d31/raxial /cell/d32/axial
addmsg /cell/d32/raxial /cell/d33/axial
addmsg /cell/d33/raxial /cell/d34/axial
addmsg /cell/d34/raxial /cell/d35/axial
addmsg /cell/d35/raxial /cell/d36/axial
addmsg /cell/d36/raxial /cell/d37/axial
addmsg /cell/d37/raxial /cell/d38/axial
addmsg /cell/d38/raxial /cell/d39/axial
addmsg /cell/d39/raxial /cell/d40/axial
addmsg /cell/d40/raxial /cell/d41/axial
addmsg /cell/d41/raxial /cell/d42/axial
addmsg /cell/d42/raxial /cell/d43/axial
addmsg /cell/d43/raxial /cell/d44/axial
addmsg /cell/d44/raxial /cell/d45/axial
addmsg /cell/d45/raxial /cell/d46/axial
addmsg /cell/d46/raxial /cell/d47/axial
addmsg /cell/d47/raxial /cell/d48/axial
addmsg /cell/d48/raxial /cell/d49/axial
addmsg /cell/d49/raxial /cell/d50/axial
addmsg /cell/d50/raxial /cell/d51/axial
addmsg /cell/d51/raxial /cell/d52/axial
addmsg /cell/d52/raxial /cell/d53/axial
addmsg /cell/d53/raxial /cell/d54/axial
addmsg /cell/d54/raxial /cell/d55/axial
addmsg /cell/d55/raxial /cell/d56/axial
addmsg /cell/d56/raxial /cell/d57/axial
addmsg /cell/d57/raxial /cell/d58/axial
addmsg /cell/d58/raxial /cell/d59/axial
addmsg /cell/d59/raxial /cell/d60/axial
addmsg /cell/d60/raxial /cell/d61/axial
addmsg /cell/d61/raxial /cell/d62/axial
addmsg /cell/d62/raxial /cell/d63/axial
addmsg /cell/d63/raxial /cell/d64/axial
addmsg /cell/d64/raxial /cell/d65/axial
addmsg /cell/d65/raxial /cell/d66/axial
addmsg /cell/d66/raxial /cell/d67/axial
addmsg /cell/d67/raxial /cell/d68/axial
addmsg /cell/d68/raxial /cell/d69/axial
addmsg /cell/d69/raxial /cell/d70/axial
addmsg /cell/d70/raxial /cell/d71/axial
addmsg /cell/d71/raxial /cell/d72/axial
addmsg /cell/d72/raxial /cell/d73/axial
addmsg /cell/d73/raxial /cell/d74/axial
addmsg /cell/d74/raxial /cell/d75/axial
addmsg /cell/d75/raxial /cell/d76/axial
addmsg /cell/d76/raxial /cell/d77/axial
addmsg /cell/d77/raxial /cell/d78/axial
addmsg /cell/d78/raxial /cell/d79/axial
addmsg /cell/d79/raxial /cell/d80/axial
addmsg /cell/d80/raxial /cell/d81/axial
addmsg /cell/d81/raxial /cell/d82/axial
addmsg /cell/d82/raxial /cell/d83/axial
addmsg /cell/d83/raxial /cell/d84/axial
addmsg /cell/d84/raxial /cell/d85/axial
addmsg /cell/d85/raxial /cell/d86/axial
addmsg /cell/d86/raxial /cell/d87/axial
addmsg /cell/d87/raxial /cell/d88/axial
addmsg /cell/d88/raxial /cell/d89/axial
addmsg /cell/d89/raxial /cell/d90/axial
addmsg /cell/d90/raxial /cell/d91/axial
addmsg /cell/d91/raxial /cell/d92/axial
addmsg /cell/d92/raxial /cell/d93/axial
addmsg /cell/d93/raxial /cell/d94/axial
addmsg /cell/d94/raxial /cell/d95/axial
addmsg /cell/d95/raxial /cell/d96/axial
addmsg /cell/d96/raxial /cell/d97/axial
addmsg /cell/d97/raxial /cell/d98/axial
addmsg /cell/d98/raxial /cell/d99/axial
setfield /cell/d0 Inject 0.01

create Neutral /graphs
create Plot /graphs/d0
create Plot /graphs/d1
create Plot /graphs/d2
create Plot /graphs/d3
create Plot /graphs/d9
addmsg /graphs/d0/trigPlot /cell/d0/Vm
addmsg /graphs/d1/trigPlot /cell/d1/Vm
addmsg /graphs/d2/trigPlot /cell/d2/Vm
addmsg /graphs/d3/trigPlot /cell/d3/Vm
addmsg /graphs/d9/trigPlot /cell/d9/Vm

create HSolve /solver
setfield /solver path "/cell/##"
setclock 1 0.001
setclock 0 0.001
useclock /solver 4
useclock /cell/##[TYPE=Compartment] 0
useclock /graphs/##[TYPE=Plot] 1
reset
step 3 -t
call /graphs/##[TYPE=Plot] printIn cable_t0.001.plot
quit

