repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.1
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-docstring-first
    - id: debug-statements
    - id: fix-encoding-pragma
    - id: trailing-whitespace
