#!/bin/sh

if [ -z $LD_LIBRARY_PATH ]
then
	export LD_LIBRARY_PATH=/usr/share/moose1.3/lib
else
	export LD_LIBRARY_PATH=/usr/share/moose1.3/lib:$LD_LIBRARY_PATH
fi

if [ -f $HOME/.moose/moose1.3 ]
then
	/usr/bin/moosegui-bin "$@"
else 
	mkdir $HOME/moose1.3
	echo "Copying Moose demos and documentation to your home directory.This may take some time."
	cp -R /usr/share/doc/moose1.3/DEMOS  /usr/share/doc/moose1.3/TESTS /usr/share/doc/moose1.3/README $HOME/moose1.3
	ln -s /usr/share/doc/moose1.3/DOCS $HOME/moose1.3/DOCS 
	
	if [ -d $HOME/Desktop ]
	then
		ln -s $HOME/moose1.3 $HOME/Desktop/moose1.3
	fi
	
	echo "Demos and documentation have been copied to " $HOME/moose1.3
	/usr/bin/moosegui-bin "$@"
	
	mkdir $HOME/.moose
	touch $HOME/.moose/moose1.3
fi
