# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moogliLayout.ui'
#
# Created: Mon Jan  9 21:29:27 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 601)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.canvas = canvas(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setObjectName(_fromUtf8("canvas"))
        self.horizontalLayout.addWidget(self.canvas)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.playButton = QtGui.QToolButton(self.centralwidget)
        self.playButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.playButton.setAutoRaise(True)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout_2.addWidget(self.playButton)
        self.stopButton = QtGui.QToolButton(self.centralwidget)
        self.stopButton.setAutoRaise(True)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_2.addWidget(self.stopButton)
        self.dummytoolButton = QtGui.QToolButton(self.centralwidget)
        self.dummytoolButton.setEnabled(False)
        self.dummytoolButton.setAutoRaise(True)
        self.dummytoolButton.setObjectName(_fromUtf8("dummytoolButton"))
        self.horizontalLayout_2.addWidget(self.dummytoolButton)
        self.openToolButton = QtGui.QToolButton(self.centralwidget)
        self.openToolButton.setAutoRaise(True)
        self.openToolButton.setObjectName(_fromUtf8("openToolButton"))
        self.horizontalLayout_2.addWidget(self.openToolButton)
        self.saveSnapButton = QtGui.QToolButton(self.centralwidget)
        self.saveSnapButton.setAutoRaise(True)
        self.saveSnapButton.setObjectName(_fromUtf8("saveSnapButton"))
        self.horizontalLayout_2.addWidget(self.saveSnapButton)
        self.saveMovieButton = QtGui.QToolButton(self.centralwidget)
        self.saveMovieButton.setAutoRaise(True)
        self.saveMovieButton.setObjectName(_fromUtf8("saveMovieButton"))
        self.horizontalLayout_2.addWidget(self.saveMovieButton)
        self.dummy2ToolButton = QtGui.QToolButton(self.centralwidget)
        self.dummy2ToolButton.setEnabled(False)
        self.dummy2ToolButton.setAutoRaise(True)
        self.dummy2ToolButton.setObjectName(_fromUtf8("dummy2ToolButton"))
        self.horizontalLayout_2.addWidget(self.dummy2ToolButton)
        self.plotToolButton = QtGui.QToolButton(self.centralwidget)
        self.plotToolButton.setAutoRaise(True)
        self.plotToolButton.setObjectName(_fromUtf8("plotToolButton"))
        self.horizontalLayout_2.addWidget(self.plotToolButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.timeSlider = QtGui.QSlider(self.centralwidget)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName(_fromUtf8("timeSlider"))
        self.verticalLayout.addWidget(self.timeSlider)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Export = QtGui.QMenu(self.menuFile)
        self.menu_Export.setObjectName(_fromUtf8("menu_Export"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSaveAsSnapshot = QtGui.QAction(MainWindow)
        self.actionSaveAsSnapshot.setObjectName(_fromUtf8("actionSaveAsSnapshot"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionBinProperties = QtGui.QAction(MainWindow)
        self.actionBinProperties.setObjectName(_fromUtf8("actionBinProperties"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionBlenderScript = QtGui.QAction(MainWindow)
        self.actionBlenderScript.setObjectName(_fromUtf8("actionBlenderScript"))
        self.actionClearAll = QtGui.QAction(MainWindow)
        self.actionClearAll.setObjectName(_fromUtf8("actionClearAll"))
        self.actionSaveAsMovie = QtGui.QAction(MainWindow)
        self.actionSaveAsMovie.setObjectName(_fromUtf8("actionSaveAsMovie"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.menu_Export.addAction(self.actionBlenderScript)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSaveAsMovie)
        self.menuFile.addAction(self.actionSaveAsSnapshot)
        self.menuFile.addAction(self.actionPlay)
        self.menuFile.addAction(self.actionStop)
        self.menuFile.addAction(self.actionClearAll)
        self.menuFile.addAction(self.menu_Export.menuAction())
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionBinProperties)
        self.menu_Help.addAction(self.actionDocumentation)
        self.menu_Help.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Moogli", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "||", None, QtGui.QApplication.UnicodeUTF8))
        self.dummytoolButton.setText(QtGui.QApplication.translate("MainWindow", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.openToolButton.setText(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSnapButton.setText(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.saveMovieButton.setText(QtGui.QApplication.translate("MainWindow", "sm", None, QtGui.QApplication.UnicodeUTF8))
        self.dummy2ToolButton.setText(QtGui.QApplication.translate("MainWindow", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.plotToolButton.setText(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Export.setTitle(QtGui.QApplication.translate("MainWindow", "&Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAsSnapshot.setText(QtGui.QApplication.translate("MainWindow", "Save As Sna&pshot ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAsSnapshot.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBinProperties.setText(QtGui.QApplication.translate("MainWindow", "&Bin Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("MainWindow", "&Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "&Play/Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBlenderScript.setText(QtGui.QApplication.translate("MainWindow", "Blender Script", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClearAll.setText(QtGui.QApplication.translate("MainWindow", "Clea&r All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClearAll.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAsMovie.setText(QtGui.QApplication.translate("MainWindow", "&Save As Movie", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAsMovie.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "S&top", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setShortcut(QtGui.QApplication.translate("MainWindow", "Return", None, QtGui.QApplication.UnicodeUTF8))

from canvas import canvas
