#ifndef SYNAPTICDATA_HPP
#define SYNAPTICDATA_HPP

struct SynapticData{
	/**
	 * Pointers to the number of spikes generated by the neurons of each type
	 */
	ucomp **nGeneratedSpikesHost;   // [type][neuron]    	[MPI]
	ucomp **nGeneratedSpikesDevice; //

	ucomp ***nGeneratedSpikesGpusDev;  //					[MPI]
	ucomp ***nGeneratedSpikesGpusHost; //

	/**
	 * List of generated spikes from the thread types
	 */
	ftype **genSpikeTimeListHost;	// [All types in MPI version]
	ftype **genSpikeTimeListDevice;

	/**
	 * List of generated spikes from the types of all threads
	 */
	ftype ***genSpikeTimeListGpusHost;
	ftype ***genSpikeTimeListGpusDev;

	ftype **vmListHost;
	ftype **vmListDevice;

	ftype **activationListGlobal;
	ucomp **activationListPosGlobal;
	ftype **activationListDevice;
	ucomp **activationListPosDevice;

	ftype **activationListTest;

	int totalTypes;
};


#endif
