@node Detailed Guide
@chapter In-Depth Guide to PyMOOSE
In this chapter we go through the internal details of PyMOOSE.
@menu
* Overview:: 
* Model Tree::        All elements in MOOSE are part of a Tree structure
* Id::                The unique identifier for each MOOSE object
* PyMooseBase::       Common properties of all MOOSE classes
* PyMooseContext::    Access to global functions
@end menu

@node Overview
@section Overview of PyMOOSE internals
Yet to be written.

@node Model Tree
@section Model Tree
All elements in MOOSE are part of a Tree structure.
Yet to be written.

@node Id
@section Id
The unique identifier for each MOOSE object
Yet to be written.

@node PyMooseBase
@section PyMooseBase
Common properties of all MOOSE classes
Yet to be written.

@node PyMooseContext
@section PyMooseContext
One global object that provides access to global functions.
Yet to be written.
