@node Index, Variable Index, , Top
@unnumbered Index

@menu
* Variable Index::              
* Concept Index::               
@end menu

@node Variable Index, Concept Index, Index, Index
@unnumbered Variable Index

@printindex vr


@node Concept Index, , Variable Index, Index
@unnumbered Concept Index

@printindex cp


@c Local Variables: 
@c mode: texinfo
@c TeX-master: "pymoose"
@c End: 
