# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgui.ui'
#
# Created: Wed Jun 27 14:32:28 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(799, 948)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.layoutWidget.setAutoFillBackground(False)
        self.layoutWidget.setStyleSheet(_fromUtf8(""))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout.addWidget(self.layoutWidget)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuShell_Mode = QtGui.QMenu(self.menuFile)
        self.menuShell_Mode.setObjectName(_fromUtf8("menuShell_Mode"))
        self.menuClasses = QtGui.QMenu(self.menubar)
        self.menuClasses.setEnabled(False)
        self.menuClasses.setObjectName(_fromUtf8("menuClasses"))
        self.menuBase = QtGui.QMenu(self.menuClasses)
        self.menuBase.setObjectName(_fromUtf8("menuBase"))
        self.menuBuiltins = QtGui.QMenu(self.menuClasses)
        self.menuBuiltins.setObjectName(_fromUtf8("menuBuiltins"))
        self.menuBipoPhysics = QtGui.QMenu(self.menuClasses)
        self.menuBipoPhysics.setObjectName(_fromUtf8("menuBipoPhysics"))
        self.menuKinects = QtGui.QMenu(self.menuClasses)
        self.menuKinects.setObjectName(_fromUtf8("menuKinects"))
        self.menuDevice = QtGui.QMenu(self.menuClasses)
        self.menuDevice.setObjectName(_fromUtf8("menuDevice"))
        self.menuRobot = QtGui.QMenu(self.menuClasses)
        self.menuRobot.setObjectName(_fromUtf8("menuRobot"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setEnabled(False)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setEnabled(False)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        MainWindow.setMenuBar(self.menubar)
        self.mooseObjectEditDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mooseObjectEditDock.sizePolicy().hasHeightForWidth())
        self.mooseObjectEditDock.setSizePolicy(sizePolicy)
        self.mooseObjectEditDock.setObjectName(_fromUtf8("mooseObjectEditDock"))
        self.mooseObjectEditDockContents = QtGui.QWidget()
        self.mooseObjectEditDockContents.setObjectName(_fromUtf8("mooseObjectEditDockContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mooseObjectEditDockContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mTable = ObjectEditView(self.mooseObjectEditDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mTable.sizePolicy().hasHeightForWidth())
        self.mTable.setSizePolicy(sizePolicy)
        self.mTable.setObjectName(_fromUtf8("mTable"))
        self.verticalLayout_2.addWidget(self.mTable)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_12 = QtGui.QLabel(self.mooseObjectEditDockContents)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_21.addWidget(self.label_12)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.propEditorSelParentPushButton = QtGui.QPushButton(self.mooseObjectEditDockContents)
        self.propEditorSelParentPushButton.setObjectName(_fromUtf8("propEditorSelParentPushButton"))
        self.horizontalLayout_21.addWidget(self.propEditorSelParentPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.propEditorChildListWidget = QtGui.QListWidget(self.mooseObjectEditDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propEditorChildListWidget.sizePolicy().hasHeightForWidth())
        self.propEditorChildListWidget.setSizePolicy(sizePolicy)
        self.propEditorChildListWidget.setMaximumSize(QtCore.QSize(16777215, 75))
        self.propEditorChildListWidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.propEditorChildListWidget.setAlternatingRowColors(False)
        self.propEditorChildListWidget.setObjectName(_fromUtf8("propEditorChildListWidget"))
        self.verticalLayout_2.addWidget(self.propEditorChildListWidget)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.mooseObjectEditDock.setWidget(self.mooseObjectEditDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.mooseObjectEditDock)
        self.moosePopulationEditDock = QtGui.QDockWidget(MainWindow)
        self.moosePopulationEditDock.setEnabled(True)
        self.moosePopulationEditDock.setObjectName(_fromUtf8("moosePopulationEditDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.popFilterSelectLineEdit = QtGui.QLineEdit(self.dockWidgetContents)
        self.popFilterSelectLineEdit.setObjectName(_fromUtf8("popFilterSelectLineEdit"))
        self.horizontalLayout_5.addWidget(self.popFilterSelectLineEdit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.popSelectParentPushButton = QtGui.QPushButton(self.dockWidgetContents)
        self.popSelectParentPushButton.setObjectName(_fromUtf8("popSelectParentPushButton"))
        self.horizontalLayout_5.addWidget(self.popSelectParentPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.popSelectedListWidget = QtGui.QListWidget(self.dockWidgetContents)
        self.popSelectedListWidget.setObjectName(_fromUtf8("popSelectedListWidget"))
        self.horizontalLayout_3.addWidget(self.popSelectedListWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.popCommonPropListWidget = QtGui.QListWidget(self.dockWidgetContents)
        self.popCommonPropListWidget.setObjectName(_fromUtf8("popCommonPropListWidget"))
        self.horizontalLayout_8.addWidget(self.popCommonPropListWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_9.addWidget(self.label_2)
        self.popDistrbComboBox = QtGui.QComboBox(self.dockWidgetContents)
        self.popDistrbComboBox.setObjectName(_fromUtf8("popDistrbComboBox"))
        self.popDistrbComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.popDistrbComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.popEditPushButton = QtGui.QPushButton(self.dockWidgetContents)
        self.popEditPushButton.setObjectName(_fromUtf8("popEditPushButton"))
        self.horizontalLayout_4.addWidget(self.popEditPushButton)
        self.popAddToLibPushButton = QtGui.QPushButton(self.dockWidgetContents)
        self.popAddToLibPushButton.setObjectName(_fromUtf8("popAddToLibPushButton"))
        self.horizontalLayout_4.addWidget(self.popAddToLibPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.moosePopulationEditDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.moosePopulationEditDock)
        self.mooseLibraryDock = QtGui.QDockWidget(MainWindow)
        self.mooseLibraryDock.setEnabled(True)
        self.mooseLibraryDock.setObjectName(_fromUtf8("mooseLibraryDock"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.libListWidget = QtGui.QListWidget(self.dockWidgetContents_2)
        self.libListWidget.setObjectName(_fromUtf8("libListWidget"))
        self.verticalLayout.addWidget(self.libListWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.libDeleteButton = QtGui.QPushButton(self.dockWidgetContents_2)
        self.libDeleteButton.setObjectName(_fromUtf8("libDeleteButton"))
        self.horizontalLayout_2.addWidget(self.libDeleteButton)
        self.libMakeCopiesButton = QtGui.QPushButton(self.dockWidgetContents_2)
        self.libMakeCopiesButton.setObjectName(_fromUtf8("libMakeCopiesButton"))
        self.horizontalLayout_2.addWidget(self.libMakeCopiesButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.mooseLibraryDock.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.mooseLibraryDock)
        self.mooseConnectDock = QtGui.QDockWidget(MainWindow)
        self.mooseConnectDock.setEnabled(True)
        self.mooseConnectDock.setObjectName(_fromUtf8("mooseConnectDock"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.lineEdit_2 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_11.addWidget(self.lineEdit_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.listWidget = QtGui.QListWidget(self.dockWidgetContents_3)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_4.addWidget(self.listWidget)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_10.addWidget(self.label_3)
        self.lineEdit = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_13.addWidget(self.label_6)
        self.comboBox = QtGui.QComboBox(self.dockWidgetContents_3)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_14.addWidget(self.label_7)
        self.lineEdit_4 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_14.addWidget(self.lineEdit_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.listWidget_2 = QtGui.QListWidget(self.dockWidgetContents_3)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.verticalLayout_4.addWidget(self.listWidget_2)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.label_5 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_12.addWidget(self.label_5)
        self.lineEdit_3 = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_12.addWidget(self.lineEdit_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.pushButton = QtGui.QPushButton(self.dockWidgetContents_3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_4.addWidget(self.pushButton)
        self.mooseConnectDock.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.mooseConnectDock)
        self.plotConfigDockWidget = QtGui.QDockWidget(MainWindow)
        self.plotConfigDockWidget.setObjectName(_fromUtf8("plotConfigDockWidget"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_8 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_15.addWidget(self.label_8)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.plotConfigCurrentSelectionLabel = QtGui.QLabel(self.dockWidgetContents_4)
        self.plotConfigCurrentSelectionLabel.setObjectName(_fromUtf8("plotConfigCurrentSelectionLabel"))
        self.horizontalLayout_15.addWidget(self.plotConfigCurrentSelectionLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_11 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_19.addWidget(self.label_11)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem12)
        self.plotConfigCurrentSelectionTypeLabel = QtGui.QLabel(self.dockWidgetContents_4)
        self.plotConfigCurrentSelectionTypeLabel.setObjectName(_fromUtf8("plotConfigCurrentSelectionTypeLabel"))
        self.horizontalLayout_19.addWidget(self.plotConfigCurrentSelectionTypeLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_9 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_16.addWidget(self.label_9)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.plotConfigFieldSelectionComboBox = QtGui.QComboBox(self.dockWidgetContents_4)
        self.plotConfigFieldSelectionComboBox.setObjectName(_fromUtf8("plotConfigFieldSelectionComboBox"))
        self.horizontalLayout_16.addWidget(self.plotConfigFieldSelectionComboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_10 = QtGui.QLabel(self.dockWidgetContents_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_17.addWidget(self.label_10)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem14)
        self.plotConfigWinSelectionComboBox = QtGui.QComboBox(self.dockWidgetContents_4)
        self.plotConfigWinSelectionComboBox.setObjectName(_fromUtf8("plotConfigWinSelectionComboBox"))
        self.plotConfigWinSelectionComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_17.addWidget(self.plotConfigWinSelectionComboBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.plotConfigNewWindowPushButton = QtGui.QPushButton(self.dockWidgetContents_4)
        self.plotConfigNewWindowPushButton.setObjectName(_fromUtf8("plotConfigNewWindowPushButton"))
        self.horizontalLayout_18.addWidget(self.plotConfigNewWindowPushButton)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem15)
        self.plotConfigAcceptPushButton = QtGui.QPushButton(self.dockWidgetContents_4)
        self.plotConfigAcceptPushButton.setObjectName(_fromUtf8("plotConfigAcceptPushButton"))
        self.horizontalLayout_18.addWidget(self.plotConfigAcceptPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem16)
        self.plotConfigDockWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.plotConfigDockWidget)
        self.simControlDockWidget = QtGui.QDockWidget(MainWindow)
        self.simControlDockWidget.setObjectName(_fromUtf8("simControlDockWidget"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.simControlSimdtLineEdit = QtGui.QLineEdit(self.dockWidgetContents_5)
        self.simControlSimdtLineEdit.setObjectName(_fromUtf8("simControlSimdtLineEdit"))
        self.gridLayout.addWidget(self.simControlSimdtLineEdit, 1, 2, 1, 1)
        self.simControlPlotdtLineEdit = QtGui.QLineEdit(self.dockWidgetContents_5)
        self.simControlPlotdtLineEdit.setObjectName(_fromUtf8("simControlPlotdtLineEdit"))
        self.gridLayout.addWidget(self.simControlPlotdtLineEdit, 2, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.simControlUpdatePlotdtLineEdit = QtGui.QLineEdit(self.dockWidgetContents_5)
        self.simControlUpdatePlotdtLineEdit.setObjectName(_fromUtf8("simControlUpdatePlotdtLineEdit"))
        self.gridLayout.addWidget(self.simControlUpdatePlotdtLineEdit, 3, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 0, 0, 1, 1)
        self.simControlRunTimeLineEdit = QtGui.QLineEdit(self.dockWidgetContents_5)
        self.simControlRunTimeLineEdit.setObjectName(_fromUtf8("simControlRunTimeLineEdit"))
        self.gridLayout.addWidget(self.simControlRunTimeLineEdit, 0, 2, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem18)
        self.simControlRunPushButton = QtGui.QPushButton(self.dockWidgetContents_5)
        self.simControlRunPushButton.setObjectName(_fromUtf8("simControlRunPushButton"))
        self.horizontalLayout_20.addWidget(self.simControlRunPushButton)
        self.simControlResetPushButton = QtGui.QPushButton(self.dockWidgetContents_5)
        self.simControlResetPushButton.setObjectName(_fromUtf8("simControlResetPushButton"))
        self.horizontalLayout_20.addWidget(self.simControlResetPushButton)
        self.simControlContinuePushButton = QtGui.QPushButton(self.dockWidgetContents_5)
        self.simControlContinuePushButton.setObjectName(_fromUtf8("simControlContinuePushButton"))
        self.horizontalLayout_20.addWidget(self.simControlContinuePushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_16 = QtGui.QLabel(self.dockWidgetContents_5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_22.addWidget(self.label_16)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem19)
        self.simControlCurrentTimeLabel = QtGui.QLabel(self.dockWidgetContents_5)
        self.simControlCurrentTimeLabel.setObjectName(_fromUtf8("simControlCurrentTimeLabel"))
        self.horizontalLayout_22.addWidget(self.simControlCurrentTimeLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem20)
        self.simControlDockWidget.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.simControlDockWidget)
        self.actionLoad_Model = QtGui.QAction(MainWindow)
        self.actionLoad_Model.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionLoad_Model.setObjectName(_fromUtf8("actionLoad_Model"))
        self.actionNew_Plot = QtGui.QAction(MainWindow)
        self.actionNew_Plot.setObjectName(_fromUtf8("actionNew_Plot"))
        self.actionNew_Visualization = QtGui.QAction(MainWindow)
        self.actionNew_Visualization.setObjectName(_fromUtf8("actionNew_Visualization"))
        self.actionPython = QtGui.QAction(MainWindow)
        self.actionPython.setCheckable(True)
        self.actionPython.setChecked(True)
        self.actionPython.setObjectName(_fromUtf8("actionPython"))
        self.actionGenesis = QtGui.QAction(MainWindow)
        self.actionGenesis.setCheckable(True)
        self.actionGenesis.setObjectName(_fromUtf8("actionGenesis"))
        self.actionReset_Settings = QtGui.QAction(MainWindow)
        self.actionReset_Settings.setObjectName(_fromUtf8("actionReset_Settings"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNeutral = QtGui.QAction(MainWindow)
        self.actionNeutral.setObjectName(_fromUtf8("actionNeutral"))
        self.actionTick = QtGui.QAction(MainWindow)
        self.actionTick.setObjectName(_fromUtf8("actionTick"))
        self.actionTimeTables = QtGui.QAction(MainWindow)
        self.actionTimeTables.setObjectName(_fromUtf8("actionTimeTables"))
        self.actionInterpol = QtGui.QAction(MainWindow)
        self.actionInterpol.setObjectName(_fromUtf8("actionInterpol"))
        self.actionAscFile = QtGui.QAction(MainWindow)
        self.actionAscFile.setObjectName(_fromUtf8("actionAscFile"))
        self.actionInterpol2D = QtGui.QAction(MainWindow)
        self.actionInterpol2D.setObjectName(_fromUtf8("actionInterpol2D"))
        self.actionCalculator = QtGui.QAction(MainWindow)
        self.actionCalculator.setObjectName(_fromUtf8("actionCalculator"))
        self.actionTable = QtGui.QAction(MainWindow)
        self.actionTable.setObjectName(_fromUtf8("actionTable"))
        self.actionHHChannel = QtGui.QAction(MainWindow)
        self.actionHHChannel.setObjectName(_fromUtf8("actionHHChannel"))
        self.actionCell = QtGui.QAction(MainWindow)
        self.actionCell.setObjectName(_fromUtf8("actionCell"))
        self.actionCompartment = QtGui.QAction(MainWindow)
        self.actionCompartment.setObjectName(_fromUtf8("actionCompartment"))
        self.actionGHK = QtGui.QAction(MainWindow)
        self.actionGHK.setObjectName(_fromUtf8("actionGHK"))
        self.actionHHChannel2D = QtGui.QAction(MainWindow)
        self.actionHHChannel2D.setObjectName(_fromUtf8("actionHHChannel2D"))
        self.actionMg_block = QtGui.QAction(MainWindow)
        self.actionMg_block.setObjectName(_fromUtf8("actionMg_block"))
        self.actionNerst = QtGui.QAction(MainWindow)
        self.actionNerst.setObjectName(_fromUtf8("actionNerst"))
        self.actionNMDAChan = QtGui.QAction(MainWindow)
        self.actionNMDAChan.setObjectName(_fromUtf8("actionNMDAChan"))
        self.actionTauPump = QtGui.QAction(MainWindow)
        self.actionTauPump.setObjectName(_fromUtf8("actionTauPump"))
        self.actionSynChan = QtGui.QAction(MainWindow)
        self.actionSynChan.setObjectName(_fromUtf8("actionSynChan"))
        self.actionIntFire = QtGui.QAction(MainWindow)
        self.actionIntFire.setObjectName(_fromUtf8("actionIntFire"))
        self.actionSpikeGen = QtGui.QAction(MainWindow)
        self.actionSpikeGen.setObjectName(_fromUtf8("actionSpikeGen"))
        self.actionIzhikevichNrn = QtGui.QAction(MainWindow)
        self.actionIzhikevichNrn.setObjectName(_fromUtf8("actionIzhikevichNrn"))
        self.actionHHGate = QtGui.QAction(MainWindow)
        self.actionHHGate.setObjectName(_fromUtf8("actionHHGate"))
        self.actionHHGate2D = QtGui.QAction(MainWindow)
        self.actionHHGate2D.setObjectName(_fromUtf8("actionHHGate2D"))
        self.actionBinSynChan = QtGui.QAction(MainWindow)
        self.actionBinSynChan.setObjectName(_fromUtf8("actionBinSynChan"))
        self.actionRandomSpike = QtGui.QAction(MainWindow)
        self.actionRandomSpike.setObjectName(_fromUtf8("actionRandomSpike"))
        self.actionCaConc = QtGui.QAction(MainWindow)
        self.actionCaConc.setObjectName(_fromUtf8("actionCaConc"))
        self.actionStochSynChan = QtGui.QAction(MainWindow)
        self.actionStochSynChan.setObjectName(_fromUtf8("actionStochSynChan"))
        self.actionSymCompartment = QtGui.QAction(MainWindow)
        self.actionSymCompartment.setObjectName(_fromUtf8("actionSymCompartment"))
        self.actionScript_out = QtGui.QAction(MainWindow)
        self.actionScript_out.setObjectName(_fromUtf8("actionScript_out"))
        self.actionDifChan = QtGui.QAction(MainWindow)
        self.actionDifChan.setObjectName(_fromUtf8("actionDifChan"))
        self.actionPulseGen = QtGui.QAction(MainWindow)
        self.actionPulseGen.setObjectName(_fromUtf8("actionPulseGen"))
        self.actionDiffAmp = QtGui.QAction(MainWindow)
        self.actionDiffAmp.setObjectName(_fromUtf8("actionDiffAmp"))
        self.actionRC = QtGui.QAction(MainWindow)
        self.actionRC.setObjectName(_fromUtf8("actionRC"))
        self.actionAdaptot = QtGui.QAction(MainWindow)
        self.actionAdaptot.setObjectName(_fromUtf8("actionAdaptot"))
        self.actionSigNeur = QtGui.QAction(MainWindow)
        self.actionSigNeur.setObjectName(_fromUtf8("actionSigNeur"))
        self.actionPIDController = QtGui.QAction(MainWindow)
        self.actionPIDController.setObjectName(_fromUtf8("actionPIDController"))
        self.actionCylPanel = QtGui.QAction(MainWindow)
        self.actionCylPanel.setObjectName(_fromUtf8("actionCylPanel"))
        self.actionMolecule = QtGui.QAction(MainWindow)
        self.actionMolecule.setObjectName(_fromUtf8("actionMolecule"))
        self.actionReaction = QtGui.QAction(MainWindow)
        self.actionReaction.setObjectName(_fromUtf8("actionReaction"))
        self.actionGeometry = QtGui.QAction(MainWindow)
        self.actionGeometry.setObjectName(_fromUtf8("actionGeometry"))
        self.actionTriPanel = QtGui.QAction(MainWindow)
        self.actionTriPanel.setObjectName(_fromUtf8("actionTriPanel"))
        self.actionMathfunc = QtGui.QAction(MainWindow)
        self.actionMathfunc.setObjectName(_fromUtf8("actionMathfunc"))
        self.actionSurface = QtGui.QAction(MainWindow)
        self.actionSurface.setObjectName(_fromUtf8("actionSurface"))
        self.actionEnzyme = QtGui.QAction(MainWindow)
        self.actionEnzyme.setObjectName(_fromUtf8("actionEnzyme"))
        self.actionPanel = QtGui.QAction(MainWindow)
        self.actionPanel.setObjectName(_fromUtf8("actionPanel"))
        self.actionSpherePanel = QtGui.QAction(MainWindow)
        self.actionSpherePanel.setObjectName(_fromUtf8("actionSpherePanel"))
        self.actionParticle = QtGui.QAction(MainWindow)
        self.actionParticle.setObjectName(_fromUtf8("actionParticle"))
        self.actionHemispherePanel = QtGui.QAction(MainWindow)
        self.actionHemispherePanel.setObjectName(_fromUtf8("actionHemispherePanel"))
        self.actionRectPanel = QtGui.QAction(MainWindow)
        self.actionRectPanel.setObjectName(_fromUtf8("actionRectPanel"))
        self.actionKinPlaceHolder = QtGui.QAction(MainWindow)
        self.actionKinPlaceHolder.setObjectName(_fromUtf8("actionKinPlaceHolder"))
        self.actionDiskHolder = QtGui.QAction(MainWindow)
        self.actionDiskHolder.setObjectName(_fromUtf8("actionDiskHolder"))
        self.actionKinComprt = QtGui.QAction(MainWindow)
        self.actionKinComprt.setObjectName(_fromUtf8("actionKinComprt"))
        self.actionMoose_Tree = QtGui.QAction(MainWindow)
        self.actionMoose_Tree.setCheckable(True)
        self.actionMoose_Tree.setObjectName(_fromUtf8("actionMoose_Tree"))
        self.actionMoose_Shell = QtGui.QAction(MainWindow)
        self.actionMoose_Shell.setCheckable(True)
        self.actionMoose_Shell.setObjectName(_fromUtf8("actionMoose_Shell"))
        self.actionObject_Editor = QtGui.QAction(MainWindow)
        self.actionObject_Editor.setCheckable(True)
        self.actionObject_Editor.setObjectName(_fromUtf8("actionObject_Editor"))
        self.actionSimulation_Control = QtGui.QAction(MainWindow)
        self.actionSimulation_Control.setCheckable(True)
        self.actionSimulation_Control.setObjectName(_fromUtf8("actionSimulation_Control"))
        self.actionAdd_I_Clamp = QtGui.QAction(MainWindow)
        self.actionAdd_I_Clamp.setObjectName(_fromUtf8("actionAdd_I_Clamp"))
        self.actionAdd_V_Clamp = QtGui.QAction(MainWindow)
        self.actionAdd_V_Clamp.setObjectName(_fromUtf8("actionAdd_V_Clamp"))
        self.actionFirst_Time_Wizard = QtGui.QAction(MainWindow)
        self.actionFirst_Time_Wizard.setObjectName(_fromUtf8("actionFirst_Time_Wizard"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionDemos = QtGui.QAction(MainWindow)
        self.actionDemos.setObjectName(_fromUtf8("actionDemos"))
        self.actionReport_a_Bug = QtGui.QAction(MainWindow)
        self.actionReport_a_Bug.setObjectName(_fromUtf8("actionReport_a_Bug"))
        self.actionRequest_a_Feature = QtGui.QAction(MainWindow)
        self.actionRequest_a_Feature.setObjectName(_fromUtf8("actionRequest_a_Feature"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionRun = QtGui.QAction(MainWindow)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionReset = QtGui.QAction(MainWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionContinue = QtGui.QAction(MainWindow)
        self.actionContinue.setObjectName(_fromUtf8("actionContinue"))
        self.menuShell_Mode.addAction(self.actionPython)
        self.menuShell_Mode.addAction(self.actionGenesis)
        self.menuFile.addAction(self.actionLoad_Model)
        self.menuFile.addAction(self.actionNew_Plot)
        self.menuFile.addAction(self.menuShell_Mode.menuAction())
        self.menuFile.addAction(self.actionReset_Settings)
        self.menuFile.addAction(self.actionQuit)
        self.menuBase.addAction(self.actionNeutral)
        self.menuBase.addAction(self.actionTick)
        self.menuBuiltins.addAction(self.actionTimeTables)
        self.menuBuiltins.addAction(self.actionInterpol)
        self.menuBuiltins.addAction(self.actionAscFile)
        self.menuBuiltins.addAction(self.actionInterpol2D)
        self.menuBuiltins.addAction(self.actionCalculator)
        self.menuBuiltins.addAction(self.actionTable)
        self.menuBipoPhysics.addAction(self.actionHHChannel)
        self.menuBipoPhysics.addAction(self.actionCell)
        self.menuBipoPhysics.addAction(self.actionCompartment)
        self.menuBipoPhysics.addAction(self.actionMg_block)
        self.menuBipoPhysics.addAction(self.actionCaConc)
        self.menuBipoPhysics.addAction(self.actionNerst)
        self.menuBipoPhysics.addAction(self.actionTauPump)
        self.menuBipoPhysics.addAction(self.actionIntFire)
        self.menuBipoPhysics.addAction(self.actionIzhikevichNrn)
        self.menuBipoPhysics.addAction(self.actionSymCompartment)
        self.menuBipoPhysics.addAction(self.actionDifChan)
        self.menuBipoPhysics.addAction(self.actionRandomSpike)
        self.menuBipoPhysics.addAction(self.actionSpikeGen)
        self.menuBipoPhysics.addAction(self.actionScript_out)
        self.menuBipoPhysics.addSeparator()
        self.menuBipoPhysics.addAction(self.actionHHGate)
        self.menuBipoPhysics.addAction(self.actionHHGate2D)
        self.menuBipoPhysics.addAction(self.actionGHK)
        self.menuBipoPhysics.addAction(self.actionHHChannel2D)
        self.menuBipoPhysics.addAction(self.actionNMDAChan)
        self.menuBipoPhysics.addAction(self.actionSynChan)
        self.menuBipoPhysics.addAction(self.actionBinSynChan)
        self.menuBipoPhysics.addAction(self.actionStochSynChan)
        self.menuKinects.addAction(self.actionMolecule)
        self.menuKinects.addAction(self.actionReaction)
        self.menuKinects.addAction(self.actionSurface)
        self.menuKinects.addAction(self.actionEnzyme)
        self.menuKinects.addAction(self.actionParticle)
        self.menuKinects.addAction(self.actionGeometry)
        self.menuKinects.addAction(self.actionMathfunc)
        self.menuKinects.addAction(self.actionKinComprt)
        self.menuKinects.addAction(self.actionKinPlaceHolder)
        self.menuKinects.addSeparator()
        self.menuKinects.addAction(self.actionPanel)
        self.menuKinects.addAction(self.actionTriPanel)
        self.menuKinects.addAction(self.actionCylPanel)
        self.menuKinects.addAction(self.actionDiskHolder)
        self.menuKinects.addAction(self.actionRectPanel)
        self.menuKinects.addAction(self.actionSpherePanel)
        self.menuKinects.addAction(self.actionHemispherePanel)
        self.menuDevice.addAction(self.actionPulseGen)
        self.menuDevice.addAction(self.actionDiffAmp)
        self.menuDevice.addAction(self.actionRC)
        self.menuDevice.addAction(self.actionPIDController)
        self.menuRobot.addAction(self.actionAdaptot)
        self.menuRobot.addAction(self.actionSigNeur)
        self.menuClasses.addAction(self.menuBase.menuAction())
        self.menuClasses.addAction(self.menuBuiltins.menuAction())
        self.menuClasses.addAction(self.menuBipoPhysics.menuAction())
        self.menuClasses.addAction(self.menuKinects.menuAction())
        self.menuClasses.addAction(self.menuDevice.menuAction())
        self.menuClasses.addAction(self.menuRobot.menuAction())
        self.menuView.addAction(self.actionMoose_Tree)
        self.menuView.addAction(self.actionMoose_Shell)
        self.menuView.addAction(self.actionObject_Editor)
        self.menuView.addAction(self.actionSimulation_Control)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDemos)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionReport_a_Bug)
        self.menuHelp.addAction(self.actionRequest_a_Feature)
        self.menuRun.addAction(self.actionRun)
        self.menuRun.addAction(self.actionReset)
        self.menuRun.addAction(self.actionContinue)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuClasses.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShell_Mode.setTitle(QtGui.QApplication.translate("MainWindow", "Shell Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuClasses.setTitle(QtGui.QApplication.translate("MainWindow", "Classes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBase.setTitle(QtGui.QApplication.translate("MainWindow", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBuiltins.setTitle(QtGui.QApplication.translate("MainWindow", "Builtins", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBipoPhysics.setTitle(QtGui.QApplication.translate("MainWindow", "BioPhysics", None, QtGui.QApplication.UnicodeUTF8))
        self.menuKinects.setTitle(QtGui.QApplication.translate("MainWindow", "Kinects", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDevice.setTitle(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRobot.setTitle(QtGui.QApplication.translate("MainWindow", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRun.setTitle(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.mooseObjectEditDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Property Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Children", None, QtGui.QApplication.UnicodeUTF8))
        self.propEditorSelParentPushButton.setText(QtGui.QApplication.translate("MainWindow", "Select Parent", None, QtGui.QApplication.UnicodeUTF8))
        self.moosePopulationEditDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Population Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.popFilterSelectLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "filter", None, QtGui.QApplication.UnicodeUTF8))
        self.popSelectParentPushButton.setText(QtGui.QApplication.translate("MainWindow", "SelectParent", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Common Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Distribution: ", None, QtGui.QApplication.UnicodeUTF8))
        self.popDistrbComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.popEditPushButton.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.popAddToLibPushButton.setText(QtGui.QApplication.translate("MainWindow", "AddToLibrary", None, QtGui.QApplication.UnicodeUTF8))
        self.mooseLibraryDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Library", None, QtGui.QApplication.UnicodeUTF8))
        self.libDeleteButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.libMakeCopiesButton.setText(QtGui.QApplication.translate("MainWindow", "MakeCopies", None, QtGui.QApplication.UnicodeUTF8))
        self.mooseConnectDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Connect Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Sources (Current Selection):", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Source field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Connect via", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "one2one", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Target", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_4.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Target field", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.plotConfigDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Plot Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Current Selection:", None, QtGui.QApplication.UnicodeUTF8))
        self.plotConfigCurrentSelectionLabel.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Type: ", None, QtGui.QApplication.UnicodeUTF8))
        self.plotConfigCurrentSelectionTypeLabel.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Plot Field:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Plot Window:", None, QtGui.QApplication.UnicodeUTF8))
        self.plotConfigWinSelectionComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Plot Window 1", None, QtGui.QApplication.UnicodeUTF8))
        self.plotConfigNewWindowPushButton.setText(QtGui.QApplication.translate("MainWindow", "New Plot Window", None, QtGui.QApplication.UnicodeUTF8))
        self.plotConfigAcceptPushButton.setText(QtGui.QApplication.translate("MainWindow", "Okay", None, QtGui.QApplication.UnicodeUTF8))
        self.simControlDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Simulation Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Plotdt:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Update Plotdt:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Simdt:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Run Time", None, QtGui.QApplication.UnicodeUTF8))
        self.simControlRunPushButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.simControlResetPushButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.simControlContinuePushButton.setText(QtGui.QApplication.translate("MainWindow", "Continue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Current Time: ", None, QtGui.QApplication.UnicodeUTF8))
        self.simControlCurrentTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Model.setText(QtGui.QApplication.translate("MainWindow", "Load Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Model.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Plot.setText(QtGui.QApplication.translate("MainWindow", "Save Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Visualization.setText(QtGui.QApplication.translate("MainWindow", "New Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPython.setText(QtGui.QApplication.translate("MainWindow", "Python", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenesis.setText(QtGui.QApplication.translate("MainWindow", "Genesis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Settings.setText(QtGui.QApplication.translate("MainWindow", "Reset Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNeutral.setText(QtGui.QApplication.translate("MainWindow", "Neutral", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTick.setText(QtGui.QApplication.translate("MainWindow", "Tick", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTimeTables.setText(QtGui.QApplication.translate("MainWindow", "TimeTable", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInterpol.setText(QtGui.QApplication.translate("MainWindow", "Interpol", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAscFile.setText(QtGui.QApplication.translate("MainWindow", "AscFile", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInterpol2D.setText(QtGui.QApplication.translate("MainWindow", "Interpol2D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculator.setText(QtGui.QApplication.translate("MainWindow", "Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTable.setText(QtGui.QApplication.translate("MainWindow", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHHChannel.setText(QtGui.QApplication.translate("MainWindow", "Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCell.setText(QtGui.QApplication.translate("MainWindow", "Compartment", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompartment.setText(QtGui.QApplication.translate("MainWindow", "GHK", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGHK.setText(QtGui.QApplication.translate("MainWindow", "HHChannel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHHChannel2D.setText(QtGui.QApplication.translate("MainWindow", "HHChannel2D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMg_block.setText(QtGui.QApplication.translate("MainWindow", "Mg_block", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNerst.setText(QtGui.QApplication.translate("MainWindow", "Nernst", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNMDAChan.setText(QtGui.QApplication.translate("MainWindow", "NMDAChan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTauPump.setText(QtGui.QApplication.translate("MainWindow", "TauPump", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSynChan.setText(QtGui.QApplication.translate("MainWindow", "SynChan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIntFire.setText(QtGui.QApplication.translate("MainWindow", "IntFire", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpikeGen.setText(QtGui.QApplication.translate("MainWindow", "SpikeGen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIzhikevichNrn.setText(QtGui.QApplication.translate("MainWindow", "IzhikevichNrn", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHHGate.setText(QtGui.QApplication.translate("MainWindow", "HHGate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHHGate2D.setText(QtGui.QApplication.translate("MainWindow", "HHGate2D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBinSynChan.setText(QtGui.QApplication.translate("MainWindow", "BinSynChan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRandomSpike.setText(QtGui.QApplication.translate("MainWindow", "RandomSpike", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCaConc.setText(QtGui.QApplication.translate("MainWindow", "CaConc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStochSynChan.setText(QtGui.QApplication.translate("MainWindow", "StochSynChan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSymCompartment.setText(QtGui.QApplication.translate("MainWindow", "SymCompartment", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScript_out.setText(QtGui.QApplication.translate("MainWindow", "script_out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDifChan.setText(QtGui.QApplication.translate("MainWindow", "DifShell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPulseGen.setText(QtGui.QApplication.translate("MainWindow", "PulseGen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiffAmp.setText(QtGui.QApplication.translate("MainWindow", "DiffAmp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRC.setText(QtGui.QApplication.translate("MainWindow", "RC", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdaptot.setText(QtGui.QApplication.translate("MainWindow", "Adaptor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSigNeur.setText(QtGui.QApplication.translate("MainWindow", "SigNeur", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPIDController.setText(QtGui.QApplication.translate("MainWindow", "PIDController", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCylPanel.setText(QtGui.QApplication.translate("MainWindow", "CylPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMolecule.setText(QtGui.QApplication.translate("MainWindow", "Molecule", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReaction.setText(QtGui.QApplication.translate("MainWindow", "Reaction", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeometry.setText(QtGui.QApplication.translate("MainWindow", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTriPanel.setText(QtGui.QApplication.translate("MainWindow", "TriPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMathfunc.setText(QtGui.QApplication.translate("MainWindow", "MathFunc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSurface.setText(QtGui.QApplication.translate("MainWindow", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnzyme.setText(QtGui.QApplication.translate("MainWindow", "Enzyme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPanel.setText(QtGui.QApplication.translate("MainWindow", "Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpherePanel.setText(QtGui.QApplication.translate("MainWindow", "SpherePanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionParticle.setText(QtGui.QApplication.translate("MainWindow", "Particle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHemispherePanel.setText(QtGui.QApplication.translate("MainWindow", "HemispherePanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRectPanel.setText(QtGui.QApplication.translate("MainWindow", "RectPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKinPlaceHolder.setText(QtGui.QApplication.translate("MainWindow", "KinPlaceHolder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiskHolder.setText(QtGui.QApplication.translate("MainWindow", "DiskPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKinComprt.setText(QtGui.QApplication.translate("MainWindow", "KinCompt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMoose_Tree.setText(QtGui.QApplication.translate("MainWindow", "Moose Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMoose_Shell.setText(QtGui.QApplication.translate("MainWindow", "Moose Shell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionObject_Editor.setText(QtGui.QApplication.translate("MainWindow", "Property Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulation_Control.setText(QtGui.QApplication.translate("MainWindow", "Simulation Control", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_I_Clamp.setText(QtGui.QApplication.translate("MainWindow", "Add I Clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_V_Clamp.setText(QtGui.QApplication.translate("MainWindow", "Add V Clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst_Time_Wizard.setText(QtGui.QApplication.translate("MainWindow", "First Time Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("MainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDemos.setText(QtGui.QApplication.translate("MainWindow", "Demos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport_a_Bug.setText(QtGui.QApplication.translate("MainWindow", "Report a Bug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRequest_a_Feature.setText(QtGui.QApplication.translate("MainWindow", "Request a Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContinue.setText(QtGui.QApplication.translate("MainWindow", "Continue", None, QtGui.QApplication.UnicodeUTF8))

from objectedit import ObjectEditView
