# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgui.ui'
#
# Created: Sat May 12 00:02:46 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(852, 559)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.layoutWidget.setAutoFillBackground(False)
        self.layoutWidget.setStyleSheet(_fromUtf8(""))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout.addWidget(self.layoutWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuShell_Mode = QtGui.QMenu(self.menuFile)
        self.menuShell_Mode.setObjectName(_fromUtf8("menuShell_Mode"))
        self.menuClasses = QtGui.QMenu(self.menubar)
        self.menuClasses.setObjectName(_fromUtf8("menuClasses"))
        self.menuBase = QtGui.QMenu(self.menuClasses)
        self.menuBase.setObjectName(_fromUtf8("menuBase"))
        self.menuBuiltins = QtGui.QMenu(self.menuClasses)
        self.menuBuiltins.setObjectName(_fromUtf8("menuBuiltins"))
        self.menuBipoPhysics = QtGui.QMenu(self.menuClasses)
        self.menuBipoPhysics.setObjectName(_fromUtf8("menuBipoPhysics"))
        self.menuKinects = QtGui.QMenu(self.menuClasses)
        self.menuKinects.setObjectName(_fromUtf8("menuKinects"))
        self.menuDevice = QtGui.QMenu(self.menuClasses)
        self.menuDevice.setObjectName(_fromUtf8("menuDevice"))
        self.menuRobot = QtGui.QMenu(self.menuClasses)
        self.menuRobot.setObjectName(_fromUtf8("menuRobot"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.mooseObjectEditDock = QtGui.QDockWidget(MainWindow)
        self.mooseObjectEditDock.setObjectName(_fromUtf8("mooseObjectEditDock"))
        self.mooseObjectEditDockContents = QtGui.QWidget()
        self.mooseObjectEditDockContents.setObjectName(_fromUtf8("mooseObjectEditDockContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mooseObjectEditDockContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mTable = ObjectEditView(self.mooseObjectEditDockContents)
        self.mTable.setObjectName(_fromUtf8("mTable"))
        self.verticalLayout_2.addWidget(self.mTable)
        self.mooseObjectEditDock.setWidget(self.mooseObjectEditDockContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.mooseObjectEditDock)
        self.actionLoad_Model = QtGui.QAction(MainWindow)
        self.actionLoad_Model.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionLoad_Model.setObjectName(_fromUtf8("actionLoad_Model"))
        self.actionNew_Plot = QtGui.QAction(MainWindow)
        self.actionNew_Plot.setObjectName(_fromUtf8("actionNew_Plot"))
        self.actionNew_Visualization = QtGui.QAction(MainWindow)
        self.actionNew_Visualization.setObjectName(_fromUtf8("actionNew_Visualization"))
        self.actionPython = QtGui.QAction(MainWindow)
        self.actionPython.setCheckable(True)
        self.actionPython.setChecked(True)
        self.actionPython.setObjectName(_fromUtf8("actionPython"))
        self.actionGenesis = QtGui.QAction(MainWindow)
        self.actionGenesis.setCheckable(True)
        self.actionGenesis.setObjectName(_fromUtf8("actionGenesis"))
        self.actionReset_Settings = QtGui.QAction(MainWindow)
        self.actionReset_Settings.setObjectName(_fromUtf8("actionReset_Settings"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNeutral = QtGui.QAction(MainWindow)
        self.actionNeutral.setObjectName(_fromUtf8("actionNeutral"))
        self.actionTick = QtGui.QAction(MainWindow)
        self.actionTick.setObjectName(_fromUtf8("actionTick"))
        self.actionTimeTables = QtGui.QAction(MainWindow)
        self.actionTimeTables.setObjectName(_fromUtf8("actionTimeTables"))
        self.actionInterpol = QtGui.QAction(MainWindow)
        self.actionInterpol.setObjectName(_fromUtf8("actionInterpol"))
        self.actionAscFile = QtGui.QAction(MainWindow)
        self.actionAscFile.setObjectName(_fromUtf8("actionAscFile"))
        self.actionInterpol2D = QtGui.QAction(MainWindow)
        self.actionInterpol2D.setObjectName(_fromUtf8("actionInterpol2D"))
        self.actionCalculator = QtGui.QAction(MainWindow)
        self.actionCalculator.setObjectName(_fromUtf8("actionCalculator"))
        self.actionTable = QtGui.QAction(MainWindow)
        self.actionTable.setObjectName(_fromUtf8("actionTable"))
        self.actionHHChannel = QtGui.QAction(MainWindow)
        self.actionHHChannel.setObjectName(_fromUtf8("actionHHChannel"))
        self.actionCell = QtGui.QAction(MainWindow)
        self.actionCell.setObjectName(_fromUtf8("actionCell"))
        self.actionCompartment = QtGui.QAction(MainWindow)
        self.actionCompartment.setObjectName(_fromUtf8("actionCompartment"))
        self.actionGHK = QtGui.QAction(MainWindow)
        self.actionGHK.setObjectName(_fromUtf8("actionGHK"))
        self.actionHHChannel2D = QtGui.QAction(MainWindow)
        self.actionHHChannel2D.setObjectName(_fromUtf8("actionHHChannel2D"))
        self.actionMg_block = QtGui.QAction(MainWindow)
        self.actionMg_block.setObjectName(_fromUtf8("actionMg_block"))
        self.actionNerst = QtGui.QAction(MainWindow)
        self.actionNerst.setObjectName(_fromUtf8("actionNerst"))
        self.actionNMDAChan = QtGui.QAction(MainWindow)
        self.actionNMDAChan.setObjectName(_fromUtf8("actionNMDAChan"))
        self.actionTauPump = QtGui.QAction(MainWindow)
        self.actionTauPump.setObjectName(_fromUtf8("actionTauPump"))
        self.actionSynChan = QtGui.QAction(MainWindow)
        self.actionSynChan.setObjectName(_fromUtf8("actionSynChan"))
        self.actionIntFire = QtGui.QAction(MainWindow)
        self.actionIntFire.setObjectName(_fromUtf8("actionIntFire"))
        self.actionSpikeGen = QtGui.QAction(MainWindow)
        self.actionSpikeGen.setObjectName(_fromUtf8("actionSpikeGen"))
        self.actionIzhikevichNrn = QtGui.QAction(MainWindow)
        self.actionIzhikevichNrn.setObjectName(_fromUtf8("actionIzhikevichNrn"))
        self.actionHHGate = QtGui.QAction(MainWindow)
        self.actionHHGate.setObjectName(_fromUtf8("actionHHGate"))
        self.actionHHGate2D = QtGui.QAction(MainWindow)
        self.actionHHGate2D.setObjectName(_fromUtf8("actionHHGate2D"))
        self.actionBinSynChan = QtGui.QAction(MainWindow)
        self.actionBinSynChan.setObjectName(_fromUtf8("actionBinSynChan"))
        self.actionRandomSpike = QtGui.QAction(MainWindow)
        self.actionRandomSpike.setObjectName(_fromUtf8("actionRandomSpike"))
        self.actionCaConc = QtGui.QAction(MainWindow)
        self.actionCaConc.setObjectName(_fromUtf8("actionCaConc"))
        self.actionStochSynChan = QtGui.QAction(MainWindow)
        self.actionStochSynChan.setObjectName(_fromUtf8("actionStochSynChan"))
        self.actionSymCompartment = QtGui.QAction(MainWindow)
        self.actionSymCompartment.setObjectName(_fromUtf8("actionSymCompartment"))
        self.actionScript_out = QtGui.QAction(MainWindow)
        self.actionScript_out.setObjectName(_fromUtf8("actionScript_out"))
        self.actionDifChan = QtGui.QAction(MainWindow)
        self.actionDifChan.setObjectName(_fromUtf8("actionDifChan"))
        self.actionPulseGen = QtGui.QAction(MainWindow)
        self.actionPulseGen.setObjectName(_fromUtf8("actionPulseGen"))
        self.actionDiffAmp = QtGui.QAction(MainWindow)
        self.actionDiffAmp.setObjectName(_fromUtf8("actionDiffAmp"))
        self.actionRC = QtGui.QAction(MainWindow)
        self.actionRC.setObjectName(_fromUtf8("actionRC"))
        self.actionAdaptot = QtGui.QAction(MainWindow)
        self.actionAdaptot.setObjectName(_fromUtf8("actionAdaptot"))
        self.actionSigNeur = QtGui.QAction(MainWindow)
        self.actionSigNeur.setObjectName(_fromUtf8("actionSigNeur"))
        self.actionPIDController = QtGui.QAction(MainWindow)
        self.actionPIDController.setObjectName(_fromUtf8("actionPIDController"))
        self.actionCylPanel = QtGui.QAction(MainWindow)
        self.actionCylPanel.setObjectName(_fromUtf8("actionCylPanel"))
        self.actionMolecule = QtGui.QAction(MainWindow)
        self.actionMolecule.setObjectName(_fromUtf8("actionMolecule"))
        self.actionReaction = QtGui.QAction(MainWindow)
        self.actionReaction.setObjectName(_fromUtf8("actionReaction"))
        self.actionGeometry = QtGui.QAction(MainWindow)
        self.actionGeometry.setObjectName(_fromUtf8("actionGeometry"))
        self.actionTriPanel = QtGui.QAction(MainWindow)
        self.actionTriPanel.setObjectName(_fromUtf8("actionTriPanel"))
        self.actionMathfunc = QtGui.QAction(MainWindow)
        self.actionMathfunc.setObjectName(_fromUtf8("actionMathfunc"))
        self.actionSurface = QtGui.QAction(MainWindow)
        self.actionSurface.setObjectName(_fromUtf8("actionSurface"))
        self.actionEnzyme = QtGui.QAction(MainWindow)
        self.actionEnzyme.setObjectName(_fromUtf8("actionEnzyme"))
        self.actionPanel = QtGui.QAction(MainWindow)
        self.actionPanel.setObjectName(_fromUtf8("actionPanel"))
        self.actionSpherePanel = QtGui.QAction(MainWindow)
        self.actionSpherePanel.setObjectName(_fromUtf8("actionSpherePanel"))
        self.actionParticle = QtGui.QAction(MainWindow)
        self.actionParticle.setObjectName(_fromUtf8("actionParticle"))
        self.actionHemispherePanel = QtGui.QAction(MainWindow)
        self.actionHemispherePanel.setObjectName(_fromUtf8("actionHemispherePanel"))
        self.actionRectPanel = QtGui.QAction(MainWindow)
        self.actionRectPanel.setObjectName(_fromUtf8("actionRectPanel"))
        self.actionKinPlaceHolder = QtGui.QAction(MainWindow)
        self.actionKinPlaceHolder.setObjectName(_fromUtf8("actionKinPlaceHolder"))
        self.actionDiskHolder = QtGui.QAction(MainWindow)
        self.actionDiskHolder.setObjectName(_fromUtf8("actionDiskHolder"))
        self.actionKinComprt = QtGui.QAction(MainWindow)
        self.actionKinComprt.setObjectName(_fromUtf8("actionKinComprt"))
        self.actionMoose_Tree = QtGui.QAction(MainWindow)
        self.actionMoose_Tree.setCheckable(True)
        self.actionMoose_Tree.setObjectName(_fromUtf8("actionMoose_Tree"))
        self.actionMoose_Shell = QtGui.QAction(MainWindow)
        self.actionMoose_Shell.setCheckable(True)
        self.actionMoose_Shell.setObjectName(_fromUtf8("actionMoose_Shell"))
        self.actionObject_Editor = QtGui.QAction(MainWindow)
        self.actionObject_Editor.setCheckable(True)
        self.actionObject_Editor.setObjectName(_fromUtf8("actionObject_Editor"))
        self.actionSimulation_Control = QtGui.QAction(MainWindow)
        self.actionSimulation_Control.setCheckable(True)
        self.actionSimulation_Control.setObjectName(_fromUtf8("actionSimulation_Control"))
        self.actionAdd_I_Clamp = QtGui.QAction(MainWindow)
        self.actionAdd_I_Clamp.setObjectName(_fromUtf8("actionAdd_I_Clamp"))
        self.actionAdd_V_Clamp = QtGui.QAction(MainWindow)
        self.actionAdd_V_Clamp.setObjectName(_fromUtf8("actionAdd_V_Clamp"))
        self.actionFirst_Time_Wizard = QtGui.QAction(MainWindow)
        self.actionFirst_Time_Wizard.setObjectName(_fromUtf8("actionFirst_Time_Wizard"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionDemos = QtGui.QAction(MainWindow)
        self.actionDemos.setObjectName(_fromUtf8("actionDemos"))
        self.actionReport_a_Bug = QtGui.QAction(MainWindow)
        self.actionReport_a_Bug.setObjectName(_fromUtf8("actionReport_a_Bug"))
        self.actionRequest_a_Feature = QtGui.QAction(MainWindow)
        self.actionRequest_a_Feature.setObjectName(_fromUtf8("actionRequest_a_Feature"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuShell_Mode.addAction(self.actionPython)
        self.menuShell_Mode.addAction(self.actionGenesis)
        self.menuFile.addAction(self.actionLoad_Model)
        self.menuFile.addAction(self.actionNew_Plot)
        self.menuFile.addAction(self.menuShell_Mode.menuAction())
        self.menuFile.addAction(self.actionFirst_Time_Wizard)
        self.menuFile.addAction(self.actionReset_Settings)
        self.menuFile.addAction(self.actionQuit)
        self.menuBase.addAction(self.actionNeutral)
        self.menuBase.addAction(self.actionTick)
        self.menuBuiltins.addAction(self.actionTimeTables)
        self.menuBuiltins.addAction(self.actionInterpol)
        self.menuBuiltins.addAction(self.actionAscFile)
        self.menuBuiltins.addAction(self.actionInterpol2D)
        self.menuBuiltins.addAction(self.actionCalculator)
        self.menuBuiltins.addAction(self.actionTable)
        self.menuBipoPhysics.addAction(self.actionHHChannel)
        self.menuBipoPhysics.addAction(self.actionCell)
        self.menuBipoPhysics.addAction(self.actionCompartment)
        self.menuBipoPhysics.addAction(self.actionMg_block)
        self.menuBipoPhysics.addAction(self.actionCaConc)
        self.menuBipoPhysics.addAction(self.actionNerst)
        self.menuBipoPhysics.addAction(self.actionTauPump)
        self.menuBipoPhysics.addAction(self.actionIntFire)
        self.menuBipoPhysics.addAction(self.actionIzhikevichNrn)
        self.menuBipoPhysics.addAction(self.actionSymCompartment)
        self.menuBipoPhysics.addAction(self.actionDifChan)
        self.menuBipoPhysics.addAction(self.actionRandomSpike)
        self.menuBipoPhysics.addAction(self.actionSpikeGen)
        self.menuBipoPhysics.addAction(self.actionScript_out)
        self.menuBipoPhysics.addSeparator()
        self.menuBipoPhysics.addAction(self.actionHHGate)
        self.menuBipoPhysics.addAction(self.actionHHGate2D)
        self.menuBipoPhysics.addAction(self.actionGHK)
        self.menuBipoPhysics.addAction(self.actionHHChannel2D)
        self.menuBipoPhysics.addAction(self.actionNMDAChan)
        self.menuBipoPhysics.addAction(self.actionSynChan)
        self.menuBipoPhysics.addAction(self.actionBinSynChan)
        self.menuBipoPhysics.addAction(self.actionStochSynChan)
        self.menuKinects.addAction(self.actionMolecule)
        self.menuKinects.addAction(self.actionReaction)
        self.menuKinects.addAction(self.actionSurface)
        self.menuKinects.addAction(self.actionEnzyme)
        self.menuKinects.addAction(self.actionParticle)
        self.menuKinects.addAction(self.actionGeometry)
        self.menuKinects.addAction(self.actionMathfunc)
        self.menuKinects.addAction(self.actionKinComprt)
        self.menuKinects.addAction(self.actionKinPlaceHolder)
        self.menuKinects.addSeparator()
        self.menuKinects.addAction(self.actionPanel)
        self.menuKinects.addAction(self.actionTriPanel)
        self.menuKinects.addAction(self.actionCylPanel)
        self.menuKinects.addAction(self.actionDiskHolder)
        self.menuKinects.addAction(self.actionRectPanel)
        self.menuKinects.addAction(self.actionSpherePanel)
        self.menuKinects.addAction(self.actionHemispherePanel)
        self.menuDevice.addAction(self.actionPulseGen)
        self.menuDevice.addAction(self.actionDiffAmp)
        self.menuDevice.addAction(self.actionRC)
        self.menuDevice.addAction(self.actionPIDController)
        self.menuRobot.addAction(self.actionAdaptot)
        self.menuRobot.addAction(self.actionSigNeur)
        self.menuClasses.addAction(self.menuBase.menuAction())
        self.menuClasses.addAction(self.menuBuiltins.menuAction())
        self.menuClasses.addAction(self.menuBipoPhysics.menuAction())
        self.menuClasses.addAction(self.menuKinects.menuAction())
        self.menuClasses.addAction(self.menuDevice.menuAction())
        self.menuClasses.addAction(self.menuRobot.menuAction())
        self.menuView.addAction(self.actionMoose_Tree)
        self.menuView.addAction(self.actionMoose_Shell)
        self.menuView.addAction(self.actionObject_Editor)
        self.menuView.addAction(self.actionSimulation_Control)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionDemos)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionReport_a_Bug)
        self.menuHelp.addAction(self.actionRequest_a_Feature)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuClasses.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShell_Mode.setTitle(QtGui.QApplication.translate("MainWindow", "Shell Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuClasses.setTitle(QtGui.QApplication.translate("MainWindow", "Classes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBase.setTitle(QtGui.QApplication.translate("MainWindow", "Base", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBuiltins.setTitle(QtGui.QApplication.translate("MainWindow", "Builtins", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBipoPhysics.setTitle(QtGui.QApplication.translate("MainWindow", "BioPhysics", None, QtGui.QApplication.UnicodeUTF8))
        self.menuKinects.setTitle(QtGui.QApplication.translate("MainWindow", "Kinects", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDevice.setTitle(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRobot.setTitle(QtGui.QApplication.translate("MainWindow", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.mooseObjectEditDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Property Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Model.setText(QtGui.QApplication.translate("MainWindow", "Load Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Model.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Plot.setText(QtGui.QApplication.translate("MainWindow", "Save Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Visualization.setText(QtGui.QApplication.translate("MainWindow", "New Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPython.setText(QtGui.QApplication.translate("MainWindow", "Python", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenesis.setText(QtGui.QApplication.translate("MainWindow", "Genesis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Settings.setText(QtGui.QApplication.translate("MainWindow", "Reset Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNeutral.setText(QtGui.QApplication.translate("MainWindow", "Neutral", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTick.setText(QtGui.QApplication.translate("MainWindow", "Tick", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTimeTables.setText(QtGui.QApplication.translate("MainWindow", "TimeTable", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInterpol.setText(QtGui.QApplication.translate("MainWindow", "Interpol", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAscFile.setText(QtGui.QApplication.translate("MainWindow", "AscFile", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInterpol2D.setText(QtGui.QApplication.translate("MainWindow", "Interpol2D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculator.setText(QtGui.QApplication.translate("MainWindow", "Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTable.setText(QtGui.QApplication.translate("MainWindow", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHHChannel.setText(QtGui.QApplication.translate("MainWindow", "Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCell.setText(QtGui.QApplication.translate("MainWindow", "Compartment", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompartment.setText(QtGui.QApplication.translate("MainWindow", "GHK", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGHK.setText(QtGui.QApplication.translate("MainWindow", "HHChannel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHHChannel2D.setText(QtGui.QApplication.translate("MainWindow", "HHChannel2D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMg_block.setText(QtGui.QApplication.translate("MainWindow", "Mg_block", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNerst.setText(QtGui.QApplication.translate("MainWindow", "Nernst", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNMDAChan.setText(QtGui.QApplication.translate("MainWindow", "NMDAChan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTauPump.setText(QtGui.QApplication.translate("MainWindow", "TauPump", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSynChan.setText(QtGui.QApplication.translate("MainWindow", "SynChan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIntFire.setText(QtGui.QApplication.translate("MainWindow", "IntFire", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpikeGen.setText(QtGui.QApplication.translate("MainWindow", "SpikeGen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIzhikevichNrn.setText(QtGui.QApplication.translate("MainWindow", "IzhikevichNrn", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHHGate.setText(QtGui.QApplication.translate("MainWindow", "HHGate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHHGate2D.setText(QtGui.QApplication.translate("MainWindow", "HHGate2D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBinSynChan.setText(QtGui.QApplication.translate("MainWindow", "BinSynChan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRandomSpike.setText(QtGui.QApplication.translate("MainWindow", "RandomSpike", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCaConc.setText(QtGui.QApplication.translate("MainWindow", "CaConc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStochSynChan.setText(QtGui.QApplication.translate("MainWindow", "StochSynChan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSymCompartment.setText(QtGui.QApplication.translate("MainWindow", "SymCompartment", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScript_out.setText(QtGui.QApplication.translate("MainWindow", "script_out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDifChan.setText(QtGui.QApplication.translate("MainWindow", "DifShell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPulseGen.setText(QtGui.QApplication.translate("MainWindow", "PulseGen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiffAmp.setText(QtGui.QApplication.translate("MainWindow", "DiffAmp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRC.setText(QtGui.QApplication.translate("MainWindow", "RC", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdaptot.setText(QtGui.QApplication.translate("MainWindow", "Adaptor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSigNeur.setText(QtGui.QApplication.translate("MainWindow", "SigNeur", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPIDController.setText(QtGui.QApplication.translate("MainWindow", "PIDController", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCylPanel.setText(QtGui.QApplication.translate("MainWindow", "CylPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMolecule.setText(QtGui.QApplication.translate("MainWindow", "Molecule", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReaction.setText(QtGui.QApplication.translate("MainWindow", "Reaction", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeometry.setText(QtGui.QApplication.translate("MainWindow", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTriPanel.setText(QtGui.QApplication.translate("MainWindow", "TriPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMathfunc.setText(QtGui.QApplication.translate("MainWindow", "MathFunc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSurface.setText(QtGui.QApplication.translate("MainWindow", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnzyme.setText(QtGui.QApplication.translate("MainWindow", "Enzyme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPanel.setText(QtGui.QApplication.translate("MainWindow", "Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpherePanel.setText(QtGui.QApplication.translate("MainWindow", "SpherePanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionParticle.setText(QtGui.QApplication.translate("MainWindow", "Particle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHemispherePanel.setText(QtGui.QApplication.translate("MainWindow", "HemispherePanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRectPanel.setText(QtGui.QApplication.translate("MainWindow", "RectPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKinPlaceHolder.setText(QtGui.QApplication.translate("MainWindow", "KinPlaceHolder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiskHolder.setText(QtGui.QApplication.translate("MainWindow", "DiskPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKinComprt.setText(QtGui.QApplication.translate("MainWindow", "KinCompt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMoose_Tree.setText(QtGui.QApplication.translate("MainWindow", "Moose Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMoose_Shell.setText(QtGui.QApplication.translate("MainWindow", "Moose Shell", None, QtGui.QApplication.UnicodeUTF8))
        self.actionObject_Editor.setText(QtGui.QApplication.translate("MainWindow", "Property Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulation_Control.setText(QtGui.QApplication.translate("MainWindow", "Simulation Control", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_I_Clamp.setText(QtGui.QApplication.translate("MainWindow", "Add I Clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_V_Clamp.setText(QtGui.QApplication.translate("MainWindow", "Add V Clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirst_Time_Wizard.setText(QtGui.QApplication.translate("MainWindow", "First Time Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("MainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDemos.setText(QtGui.QApplication.translate("MainWindow", "Demos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport_a_Bug.setText(QtGui.QApplication.translate("MainWindow", "Report a Bug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRequest_a_Feature.setText(QtGui.QApplication.translate("MainWindow", "Request a Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

from objectedit import ObjectEditView
