# Generated by the command:
# for file in $(cat cells.txt); do echo $file; python $file >> times.txt ; done
# Then run grep 'RUNTIME' times.txt to get a list of the runtimes in sequence
deepaxoaxonic.py   :  1.037111   
deepbasket.py      :  1.128167
deepLTS.py	   :  1.392057
nontuftedRS.py	   :  1.356232
nRT.py		   :  1.517411
spinystellate.py   :  1.506574
supaxoaxonic.py	   :  1.043704
supbasket.py	   :  1.040301
supLTS.py	   :  1.484386
suppyrFRB.py	   :  2.051706
suppyrRS.py	   :  2.016963
tcr.py		   :  3.59857 
tuftedIB.py	   :  1.606878
tuftedRS.py        :  1.585079  














