##
## Makefile
##  
## Made by Subhasis Ray
## E-Mail: <subhasis at ncbs res dot in>
##
## Started on  Mon Nov  1 09:49:29 2010 Subhasis Ray
## Last update Mon Nov  1 09:49:29 2010 Subhasis Ray
## 
moosegui: moosegui.texi
	makeinfo --html moosegui.texi
	echo "html documentation generated in moosegui directory."
