#!/usr/bin/env python
# This is just a list of runtimes.
# Initial version generated by the command in bash
#$: for file in `ls test_*.hoc`; do nrngui $file >> times.txt; done 
# 
print '-----------------------------------------'
print '* Neuron Cell models run time in seconds:'
print '-----------------------------------------'

# --------------------------------------------------------------
# |    NEURON Simulation of deepaxax cell                       |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start = 1265438192.0 + 752364405e-9
end = 1265438194.0 + 060318081e-9
deepaxax = end - start
print 'DeepAxoaxonic: ', deepaxax
# --------------------------------------------------------------
# |    NEURON Simulation of deepbask cell                       |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start =  1265438194.0 + 423842562e-9
end = 1265438195.0 + 782599891e-9
deepbask = end - start
print 'DeepBasket:', deepbask
# --------------------------------------------------------------
# |    NEURON Simulation of deepLTS cell                       |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start = 1265438196.0 + 111205905e-9
end = 1265438197.0 + 444269250e-9
deepLTS = end - start
print 'DeepLTS:', deepLTS
# --------------------------------------------------------------
# |    NEURON Simulation of nontuftRS cell                     |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start = 1265438198.0 + 779433218e-9
end = 1265438199.0 + 835225363e-9
nontuftRS = end - start
print 'NontuftedRS:', nontuftRS
# --------------------------------------------------------------
# |    NEURON Simulation of nRT cell                           |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start = 1265438200.0 + 057676825e-9
end = 1265438201.0 + 403783797e-9
nRT = end - start
print 'nRT:', nRT
# --------------------------------------------------------------
# |    NEURON Simulation of spinstell cell                     |
# --------------------------------------------------------------
# Run for: 200 ms, 0.3 nA current injected at 50 ms for 50 ms
start = 1265438201.0 + 727292096e-9
end = 1265438202.0 + 990972115e-9
spinstell = end - start
print 'SpinyStellate:', spinstell
# --------------------------------------------------------------
# |    NEURON Simulation of supaxax cell                       |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start = 1265438203.0 + 375592574e-9
end = 1265438204.0 + 674899894e-9
supaxax = end - start
print 'SupAxoaxonic:', supaxax
# --------------------------------------------------------------
# |    NEURON Simulation of supbask cell                       |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start = 1265438205.0 + 013839896e-9
end = 1265438206.0 + 314242390e-9
supbask = end - start
print 'SupBasket:', supbask
# --------------------------------------------------------------
# |    NEURON Simulation of supLTS cell                        |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start = 1265438206.0 + 640986855e-9
end = 1265438207.0 + 966722104e-9
supLTS = end - start
print 'SupLTS:', supLTS
# --------------------------------------------------------------
# |    NEURON Simulation of suppyrFRB cell                     |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start = 1265438208.0 + 300260795e-9
end = 1265438209.0 + 985317136e-9
suppyrFRB = end - start
print 'SupPyrFRB:', suppyrFRB
# --------------------------------------------------------------
# |    NEURON Simulation of suppyrRS cell                       |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start = 1265438210.0 + 250914580e-9
end =  1265438211.0 + 917460396e-9
suppyrRS = end - start
print 'SupPyrRS:', suppyrRS
# --------------------------------------------------------------
# |    NEURON Simulation of TCR cell                        |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 50 ms for 50 ms
start = 1265438212.0 + 150837199e-9
end = 1265438215.0 + 027808014e-9
TCR = end - start
print 'TCR:', TCR
# --------------------------------------------------------------
# |    NEURON Simulation of tuftIB cell                        |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 0 ms for 50 ms
start = 1265438215.0 + 195223845e-9
end = 1265438216.0 + 550821973e-9
tuftIB = end - start
print 'TuftedIB:', tuftIB
# --------------------------------------------------------------
# |    NEURON Simulation of tuftRS cell                           |
# --------------------------------------------------------------
# Run for: 200 ms, inject 0.3 nA current at 0 ms for 50 ms
start = 1265438216.0 + 757925457e-9
end = 1265438218.0 + 131391850e-9
tuftRS = end - start
print 'TuftedRS:', tuftRS
