/**********************************************************************
** This program is part of 'MOOSE', the
** Messaging Object Oriented Simulation Environment,
** also known as GENESIS 3 base code.
**           copyright (C) 2003-2005 Upinder S. Bhalla. and NCBS
** It is made available under the terms of the
** GNU Lesser General Public License version 2.1
** See the file COPYING.LIB for the full notice.
**********************************************************************/

/**
 * \mainpage MOOSE Code documentation: Generated by Doxygen.
 * 
 * \section intro_sec Introduction
 * MOOSE is the Multiscale Object Oriented Simulation Environment.
 * This Doxygen-generated set of pages documents the source code of
 * MOOSE.
 *
 */

#include <iostream>
#include "header.h"
#include "moose.h"
#include "../element/Neutral.h"
#include "IdManager.h"
#ifdef USE_MPI
#include <mpi.h>
#endif

#ifdef DO_UNIT_TESTS
	extern void testBasecode();
	extern void testNeutral();
	extern void testShell();
	extern void testInterpol();
	extern void testTable();
	extern void testSched();
	extern void testSchedProcess();
	extern void testWildcard();
	extern void testBiophysics();
	extern void testKinetics();
#ifdef USE_MPI
	extern void testPostMaster();
#endif
#endif

#ifdef USE_GENESIS_PARSER
	extern Element* makeGenesisParser( );
	extern void nonblock( int state );
	extern bool nonBlockingGetLine( string& s );
#endif

void setupDefaultSchedule( 
	Element* t0, Element* t1, 
	Element* t2, Element* t3, 
	Element* t4, Element* t5,
	Element* cj)
{
	set< double >( t0, "dt", 1e-5 );
	set< double >( t1, "dt", 1e-5 );
	set< int >( t1, "stage", 1 );
	set< double >( t2, "dt", 5e-3 );
	set< double >( t3, "dt", 5e-3 );
	set< int >( t3, "stage", 1 );
	set< double >( t4, "dt", 5e-3 );
	set< double >( t5, "dt", 1.0 );
	set( cj, "resched" );
	set( cj, "reinit" );
}

int main(int argc, char** argv)
{
	unsigned int mynode = 0;
	// Create the shell on id 1.
	const Cinfo* c = Cinfo::find( "Shell" );
	assert ( c != 0 );
	const Finfo* childSrc = Element::root()->findFinfo( "childSrc" );
	assert ( childSrc != 0 );
	Element* shell = c->create( Id( 1 ), "shell" );
	assert( shell != 0 );
	bool ret = childSrc->add( Element::root(), shell, 
		shell->findFinfo( "child" ) );
	assert( ret );

#ifdef USE_MPI
// 	Element* shell =
// 			Neutral::create( "Shell", "shell", Element::root() );
	MPI::Init( argc, argv );
	unsigned int totalnodes = MPI::COMM_WORLD.Get_size();
	mynode = MPI::COMM_WORLD.Get_rank();
	Id::manager().setNodes( mynode, totalnodes );

	Element* postmasters =
			Neutral::create( "Neutral", "postmasters", Element::root());
	vector< Element* > post;
	post.reserve( totalnodes );
	for ( unsigned int i = 0; i < totalnodes; i++ ) {
		char name[10];
		if ( i != mynode ) {
			sprintf( name, "node%d", i );
			Element* p = Neutral::create(
					"PostMaster", name, postmasters );
			assert( p != 0 );
			set< unsigned int >( p, "remoteNode", i );
			post.push_back( p );
		}
	}
	Id::manager().setPostMasters( post );
	// Perhaps we will soon want to also connect up the clock ticks.
	// How do we handle different timesteps?
#else	
//	Neutral::create( "Shell", "shell", Element::root() );
#endif
	
	/**
	 * Here we set up a bunch of predefined objects, that
	 * exist simultaneously on each node.
	 */
	Element* sched =
			Neutral::create( "Neutral", "sched", Element::root() );
	// This one handles the simulation clocks
	Element* cj =
			Neutral::create( "ClockJob", "cj", sched );

	// Element* library = 
			Neutral::create( "Neutral", "library", Element::root() );
	// Element* proto = 
			Neutral::create( "Neutral", "proto", Element::root() );
	Element* solvers = 
			Neutral::create( "Neutral", "solvers", Element::root() );
	// These two should really be solver managers because there are
	// a lot of decisions to be made about how the simulation is best
	// solved. For now let the Shell deal with it.
	// Element* chem = 
			Neutral::create( "Neutral", "chem", solvers );
	// Element* neuronal = 
			Neutral::create( "Neutral", "neuronal", solvers );

#ifdef USE_MPI
	// This one handles parser and postmaster scheduling.
	Element* pj =
			Neutral::create( "ClockJob", "pj", sched );
	Element* t0 =
			Neutral::create( "ParTick", "t0", cj );
	Element* pt0 =
			Neutral::create( "ParTick", "t0", pj );
#else
	Element* t0 = Neutral::create( "Tick", "t0", cj );
	Element* t1 = Neutral::create( "Tick", "t1", cj );
	Element* t2 = Neutral::create( "Tick", "t2", cj );
	Element* t3 = Neutral::create( "Tick", "t3", cj );
	Element* t4 = Neutral::create( "Tick", "t4", cj );
	Element* t5 = Neutral::create( "Tick", "t5", cj );
#endif

#ifdef DO_UNIT_TESTS
	// if ( mynode == 0 )
	if ( 1 )
	{
		testBasecode();
		testNeutral();
		testShell();
		testInterpol();
		testTable();
		testSched();
		testSchedProcess();
		testWildcard();
		testBiophysics();
		testKinetics();
	}
#endif


#ifdef USE_MPI
	///////////////////////////////////////////////////////////////////
	//	Here we connect up the postmasters to the shell and the ParTick.
	///////////////////////////////////////////////////////////////////
	const Finfo* serialFinfo = shell->findFinfo( "serial" );
	assert( serialFinfo != 0 );
	const Finfo* masterFinfo = shell->findFinfo( "master" );
	assert( masterFinfo != 0 );
	const Finfo* slaveFinfo = shell->findFinfo( "slave" );
	assert( slaveFinfo != 0 );
	const Finfo* pollFinfo = shell->findFinfo( "pollSrc" );
	assert( pollFinfo != 0 );
	const Finfo* tickFinfo = t0->findFinfo( "parTick" );
	assert( tickFinfo != 0 );
	const Finfo* stepFinfo = pj->findFinfo( "step" );
	assert( stepFinfo != 0 );

	bool glug = (argc == 2 && 
		strcmp( argv[1], "-debug" ) == 0 );
	// Breakpoint for parallel debugging
	while ( glug );
	for ( vector< Element* >::iterator j = post.begin();
		j != post.end(); j++ ) {
		bool ret = serialFinfo->add( shell, *j, (*j)->findFinfo( "data" ) );
		// bool ret = (*j)->findFinfo( "data" )->add( *j, shell, serialFinfo );
		assert( ret );
		ret = tickFinfo->add( t0, *j, (*j)->findFinfo( "parTick" ) );
		assert( ret );
		ret = tickFinfo->add( pt0, *j, (*j)->findFinfo( "parTick" ) );
		assert( ret );

		if ( mynode == 0 ) {
			ret = masterFinfo->add( shell, *j, (*j)->findFinfo( "data" ) );
			assert( ret );
		} else {
			ret = slaveFinfo->add( shell, *j, (*j)->findFinfo( "data" ) );
			assert( ret );
		}
		/*
		cout << "On " << mynode << ", post: " << (*j)->name() << endl;
		(*j)->dumpMsgInfo();
		assert( ret );
		*/
	}
	ret = pollFinfo->add( shell, pj, pj->findFinfo( "step" ) );
	assert( ret );

	// cout << "On " << mynode << ", shell: " << shell->name() << endl;
	// shell->dumpMsgInfo();
	set( cj, "resched" );
	set( pj, "resched" );
	set( cj, "reinit" );
	set( pj, "reinit" );
#ifdef DO_UNIT_TESTS
	MPI::COMM_WORLD.Barrier();
	if ( mynode == 0 )
		cout << "\nInitialized " << totalnodes << " nodes\n";
	MPI::COMM_WORLD.Barrier();
	testPostMaster();
#endif
#endif


#ifdef USE_GENESIS_PARSER
	if ( mynode == 0 ) {
		string line = "";
		if ( argc > 1 ) {
			int len = strlen( argv[1] );
			if ( len > 3 && strcmp( argv[1] + len - 2, ".g" ) == 0 )
				line = "include";
			else if ( len > 4 && 
							strcmp( argv[1] + len - 3, ".mu" ) == 0 )
				line = "include";

			if ( line == "include" ) {
				for ( int i = 1; i < argc; i++ )
					line = line + " " + argv[ i ];
				line.push_back( '\n' );
			}
		}
		Element* sli = makeGenesisParser();
		assert( sli != 0 );

		// Need to do this before the first script is loaded, but
		// after the unit test for the parser.
		setupDefaultSchedule( t0, t1, t2, t3, t4, t5, cj );

		const Finfo* parseFinfo = sli->findFinfo( "parse" );
		assert ( parseFinfo != 0 );

		set< string >( sli, parseFinfo, line );
		set< string >( sli, parseFinfo, "\n" );

		/**
		 * Here is the key infinite loop for getting terminal input,
		 * parsing it, polling postmaster, managing GUI and other 
		 * good things.
		 */
		string s = "";
		unsigned int lineNum = 0;
		cout << "moose #" << lineNum << " > " << flush;
		while( 1 ) {
			if ( nonBlockingGetLine( s ) ) {
				set< string >( sli, parseFinfo, s );
				if ( s.find_first_not_of( " \t\n" ) != s.npos )
					lineNum++;
				s = "";
				cout << "moose #" << lineNum << " > " << flush;
			}
#ifdef USE_MPI
			// Here we poll the postmaster
			ret = set< int >( pj, stepFinfo, 1 );
#endif
			// gui stuff here maybe.
		}
	}
#endif
#ifdef USE_MPI
	if ( mynode != 0 ) {
		ret = set( shell, "poll" );
		assert( ret );
	}
	MPI::Finalize();
#endif
	cout << "done" << endl;
}
