COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.0 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   SingleSyn1 (Type: Gap junction, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/notes = ChannelML file describing a single synaptic mechanism 
   /channelml/synapse_type/@name = SingleSyn1 
   /channelml/synapse_type/status/@value = stable 
   /channelml/synapse_type/status/contributor/name = Padraig Gleeson 
   /channelml/synapse_type/notes = Description of an electrical synapse at a gap junction 
   /channelml/synapse_type/electrical_syn/@conductance = 2.0E-9 

// File from which this was generated: /home2/dilawar/Work/github/neurons_sim/neuroConstructProjects/twoNeurons/cellMechanisms/SingleSyn1/ElectSyn.xml

// XSL file with mapping to simulator: /home2/dilawar/Work/github/neurons_sim/neuroConstructProjects/twoNeurons/cellMechanisms/SingleSyn1/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file describing a single synaptic mechanism
ENDCOMMENT

? Creating synaptic mechanism for an electrical synapse
    

TITLE Channel: SingleSyn1

COMMENT
    Description of an electrical synapse at a gap junction
ENDCOMMENT


UNITS {
    (nA) = (nanoamp)
    (mV) = (millivolt)
    (uS) = (microsiemens)
}

    
NEURON {
    POINT_PROCESS SingleSyn1
    NONSPECIFIC_CURRENT i
    RANGE g, i
    RANGE weight
    
    POINTER vgap  : Using a POINTER as opposed to RANGE for serial mode
        

}

PARAMETER {
    v (millivolt)
    vgap (millivolt)
    g = 0.0000020000000000000003 (microsiemens)
    weight = 1

}


ASSIGNED {
    i (nanoamp)
}

BREAKPOINT {
    i = weight * g * (v - vgap)
} 
