#  ******************************************************
# 
#     File generated by: neuroConstruct v1.7.0
# 
#  ******************************************************

#  Including some standard Python modules 

import sys
import os

import xml.sax
import time

import logging

#  Adding working dir to Python path

if sys.path.count(os.getcwd())==0: sys.path.append(os.getcwd())

#  Including NEURON specifics

import neuron
from neuron import hoc
import nrn

sys.path.append("NeuroMLUtils")
sys.path.append("NEURONUtils")

import NetworkMLHDF5Handler
import NEURONSimUtils

#  ******************************************************
# 
#  This is the main function which will be called by the hoc file.
#  Subject to change...
# 
#  ******************************************************

def loadNetwork():
    h = hoc.HocObject()
    
    logformat = "%(name)-19s %(levelname)-5s -"+str(int(h.hostid))+"- %(message)s"
    logging.basicConfig(level=logging.INFO, format=logformat)
    log = logging.getLogger("twoNeurons")
    
    #  Adding cell template file: SimpleCell_t.hoc for cell group SimpleCellGroup
    
    h.load_file("SimpleCell_t.hoc")
    
    #  Adding cell template file: PurkinjeCell_t.hoc for cell group PurkinjeCellGroup
    
    h.load_file("PurkinjeCell_t.hoc")
    
    {load_file("SimpleCellMembrane.hoc")}
    log.log(logging.INFO, "Loading cell positions and connections from: Generated.net.h5")
    
    file_name = 'Generated.net.h5'
    
    beforeLoad = time.time()
    nmlHandler = NEURONSimUtils.NetManagerNEURON()
    curHandler = NetworkMLHDF5Handler.NetworkMLHDF5Handler(nmlHandler)
    curHandler.setNodeId(-1) 
    curHandler.parse(file_name) 
    afterLoad = time.time()
    log.log(logging.INFO, "Loaded file in "+ str(afterLoad-beforeLoad)+ " seconds on host: %d" % (int(h.hostid)))
    
    

