# CMake generated Testfile for 
# Source directory: /home/sarthak/Work/moose-core
# Build directory: /home/sarthak/Work/moose-core/_build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(moose.bin-raw-run "/home/sarthak/Work/moose-core/_build/moose.bin" "-u" "-q")
ADD_TEST(pymoose-test-synchan "/usr/bin/python" "/home/sarthak/Work/moose-core/tests/python/test_synchan.py")
SET_TESTS_PROPERTIES(pymoose-test-synchan PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/sarthak/Work/moose-core/_build/python")
ADD_TEST(pymoose-test-function "/usr/bin/python" "/home/sarthak/Work/moose-core/tests/python/test_function.py")
SET_TESTS_PROPERTIES(pymoose-test-function PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/sarthak/Work/moose-core/_build/python")
ADD_TEST(pymoose-test-vec "/usr/bin/python" "/home/sarthak/Work/moose-core/tests/python/test_vec.py")
SET_TESTS_PROPERTIES(pymoose-test-vec PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/sarthak/Work/moose-core/_build/python")
ADD_TEST(pymoose-pyrun "/usr/bin/python" "/home/sarthak/Work/moose-core/tests/python/test_pyrun.py")
SET_TESTS_PROPERTIES(pymoose-pyrun PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/sarthak/Work/moose-core/_build/python")
ADD_TEST(pymoose-neuroml-reader-test "/usr/bin/python" "/home/sarthak/Work/moose-core/tests/python/test_neuroml.py")
SET_TESTS_PROPERTIES(pymoose-neuroml-reader-test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/sarthak/Work/moose-core/_build/python")
ADD_TEST(pymoose-nsdf-sanity-test "/usr/bin/python" "/home/sarthak/Work/moose-core/tests/python/test_nsdf.py")
SET_TESTS_PROPERTIES(pymoose-nsdf-sanity-test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/sarthak/Work/moose-core/_build/python")
ADD_TEST(pymoose-test-basic-sbml-support "/usr/bin/python" "/home/sarthak/Work/moose-core/tests/python/test_sbml_support.py")
SET_TESTS_PROPERTIES(pymoose-test-basic-sbml-support PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/sarthak/Work/moose-core/_build/python")
ADD_TEST(pymoose-test-rng "/home/sarthak/Work/moose-core/tests/python/test_random_gen.sh")
SET_TESTS_PROPERTIES(pymoose-test-rng PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/sarthak/Work/moose-core/_build/python")
ADD_TEST(pymoose-test-streamer "/usr/bin/python" "/home/sarthak/Work/moose-core/tests/python/test_streamer.py")
SET_TESTS_PROPERTIES(pymoose-test-streamer PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/sarthak/Work/moose-core/_build/python")
ADD_TEST(pymoose-test-streaming_in_tables "/usr/bin/python" "/home/sarthak/Work/moose-core/tests/python/test_table_streaming_support.py")
SET_TESTS_PROPERTIES(pymoose-test-streaming_in_tables PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/sarthak/Work/moose-core/_build/python")
SUBDIRS(basecode)
SUBDIRS(msg)
SUBDIRS(shell)
SUBDIRS(randnum)
SUBDIRS(scheduling)
SUBDIRS(biophysics)
SUBDIRS(builtins)
SUBDIRS(utility)
SUBDIRS(mesh)
SUBDIRS(sbml)
SUBDIRS(mpi)
SUBDIRS(signeur)
SUBDIRS(ksolve)
SUBDIRS(hsolve)
SUBDIRS(diffusion)
SUBDIRS(device)
SUBDIRS(benchmarks)
SUBDIRS(kinetics)
SUBDIRS(synapse)
SUBDIRS(intfire)
SUBDIRS(external/muparser)
SUBDIRS(pymoose)
