name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir _build && cmake ..
    - name: make
      run: cd _build && make
    - name: make check
      run: cd _build && make check
    - name: make distcheck
      run: make distcheck
