name: Docker Image build wheels

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Wheels Using docker images
      run: docker build . --file .docker/wheel/Dockerfile --tag bhallalab/moose-wheels:$(date +%s)
