name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: "Setup Python ${{ matrix.python-version }}"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Runs a set of commands using the runners shell
    - name: Build using MSVS
      shell: bash
      run: |
        mkdir build
        cd build
        PYTHON=$(which python)
        $PYTHON -m pip install pip --upgrade
        $PYTHON -m pip install numpy pytest matplotlib setuptools
        cmake -DOPTION_PYTHON=ON -DOPTION_EXAMPLES=ON -DPython3_EXECUTABLE=$PYTHON ..
        cmake --build . --config Release 
        ctest -C Release

    - name: Upload to PyPI
      shell: bash
      env:
        SMOLDYN_PYPI_TOKEN: ${{ secrets.SMOLDYN_PYPI_TOKEN }}
      run: |
        cd build
        python -m pip install twine --upgrade
        python -m twine upload -u __token__ -p "$SMOLDYN_PYPI_TOKEN" *.whl --skip-existing || echo "Failed to upload"
